/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * @addtogroup elc_ep
 * @{
 **********************************************************************************************************************/

/* Private functions */
static void elc_deinit (void);
static void gpt_deinit (gpt_instance_ctrl_t * p_ctrl);

#define GPIO_OUTPUT_PIN (BSP_IO_PORT_13_PIN_5)

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Initializes the software and sets the links defined in the control structure. */
    fsp_err_t err = FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    uint8_t user_input[BUFFER_SIZE_DOWN] = {NULL_CHAR};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);

    APP_PRINT(EP_INFO);

    err = R_ELC_Open(&g_elc_ctrl, &g_elc_cfg);
    
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ELC module init failed */
        APP_ERR_PRINT("\r\n ** ELC module Open failed ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Open and configure GPT9 */
    err = R_GPT_Open(&g_timer0_ctrl, &g_timer0_cfg);
    
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        APP_ERR_PRINT("\r\n ** GPT module Open for Periodic mode failed ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable counter start on GPT event A */
    err = R_GPT_Enable(&g_timer0_ctrl);
    
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        gpt_deinit(&g_timer0_ctrl);
        APP_ERR_PRINT("\r\n ** GPT Enable for Periodic timer failed ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Reset the timer counter */
    uint32_t timer_value = 0U;

    /* On successful operations on ELC and GPT modules, user is asked enter any key as RTT input */
    APP_PRINT("\r\nEnter any key as RTT input. GPT counter is triggered and counter value is displayed on RTT Viewer");

    /* Wait until data is available in RTT */
    while (true)
    {
        if (APP_CHECK_DATA)
        {
            memset(&user_input[0], NULL_CHAR, BUFFER_SIZE_DOWN);
            APP_READ(user_input);

            /* Enter "HIGH" from P13_5(GPIO) to P14_0(ELC Single Port 0) to generate the event. */
            /* When P13_5 and P14_0 are connected on the board, the timer start counting
            * without calling timer start API. */
            R_IOPORT_PinWrite(&g_ioport_ctrl, GPIO_OUTPUT_PIN, BSP_IO_LEVEL_HIGH);

            /* wait a little bit for the counter to count */
            R_BSP_SoftwareDelay(10U, BSP_DELAY_UNITS_MILLISECONDS);

            /* Get the GPT count value */
            timer_status_t status;
            err = R_GPT_StatusGet(&g_timer0_ctrl, &status);
            
            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                elc_deinit();
                APP_ERR_PRINT("\r\n ** GPT get status failed ** \r\n");
                APP_ERR_TRAP(err);
            }

            timer_value = status.counter;

            /* Verify the timer_value not 0 */
            if (0 == timer_value)
            {
                elc_deinit();
                gpt_deinit(&g_timer0_ctrl);
                APP_ERR_PRINT("\r\n ** GPT counter value failed ** \r\n");
                APP_ERR_TRAP(err);
            }

            /* Display counter value on RTT Viewer */
            APP_PRINT("\r\n GPT Timer counter value: %d\r\n", timer_value);

            /* Close GPT module */
            gpt_deinit(&g_timer0_ctrl);

            /* Close ELC module */
            elc_deinit();

            APP_PRINT("\r\nExit ELC application.\r\n");
            while (true)
            {
                ;
            }
        }   
    }
}
/**********************************************************************************************************************
* End of function: hal_entry
**********************************************************************************************************************/

/***********************************************************************************************************************
 * @fn          elc_deinit
 * @brief       This function closes opened ELC module before the project ends up in an Error Trap.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void elc_deinit(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close ELC module */
    err = R_ELC_Close(&g_elc_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ELC Close failure message */
        APP_ERR_PRINT("** ELC module Close failed **  \r\n");
    }
}
/**********************************************************************************************************************
* End of function: elc_deinit
**********************************************************************************************************************/

/***********************************************************************************************************************
 * @fn          gpt_deinit
 * @brief       This function closes opened GPT module before the project ends up in an Error Trap.
 * @param[IN]   p_ctrl    Pointer to instance control.
 * @retval      None
 **********************************************************************************************************************/
static void gpt_deinit(gpt_instance_ctrl_t * p_ctrl)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close GPT timer */
    err = R_GPT_Close(p_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* GPT Close failure message */
        APP_ERR_PRINT("** GPT module Close failed **  \r\n");
    }
}
/**********************************************************************************************************************
* End of function: gpt_deinit
**********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup elc_ep)
 **********************************************************************************************************************/
