/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "xspi_init.h"
#include "ca55_start.h"
#include "cm33_fpu_start.h"
#include "common_utils.h"
#include "timer_pwm.h"
#include "uart_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_scif_uart_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry (void)
{
    fsp_err_t          err     = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize GTM in periodic mode */
    err = gtm_initialize();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("** gtm_initialize failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Start GTM */
    err = gtm_start();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("** gtm_start failed **\r\n");
        timer_gtm_deinit();
        APP_ERR_TRAP(err);
    }

    /* Initialize UART */
    err = uart_initialize();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("** uart_initialize failed **\r\n");
        timer_gtm_deinit();
        APP_ERR_TRAP(err);
    }

    /* User defined function to demonstrate UART functionality */
    err = uart_ep_demo();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("** uart_ep_demo failed **\r\n");
        timer_gtm_deinit();
        deinit_uart();
        APP_ERR_TRAP(err);
    }

    while (1)
    {
        ;
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[IN]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        if (0 == (R_SYSC_SYS_LSI_MODE_STAT_BOOTCPUSEL_Msk & R_SYSC->SYS_LSI_MODE))
        {
            xspi_open();

#if BSP_CFG_MCU_LAUNCH_CM33_FPU

            /* Load Cortex-M33_FPU program to SRAM(MCPU) */
            load_cm33fpu_prog();

            /* Release reset of Cortex-M33_FPU */
            release_reset_cm33_fpu();
#endif

#if BSP_CFG_MCU_LAUNCH_CA55

            /* Load Cortex-A55 program to SRAM(ACPU) */
            load_ca55_prog();

            xspi_close();

            /* Release reset of Cortex-A55(Core0) */
            release_reset_ca55();
#endif
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_scif_uart_ep)
 **********************************************************************************************************************/
