/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "elc_ep.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * @addtogroup r_elc_ep
 * @{
 **********************************************************************************************************************/

/* Private functions */
static void elc_deinit (void);
static void gpt_deinit (gpt_instance_ctrl_t * p_ctrl);

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char user_input[BUFFER_SIZE_DOWN] = {NULL_CHAR};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Banner information */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Open ELC driver */
    err = R_ELC_Open(&g_elc_ctrl, &g_elc_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ELC module init failed */
        APP_ERR_PRINT("\r\n** R_ELC_Open API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Open Timer in PWM mode */
    err = R_GPT_Open(&g_timer_pwm_ctrl, &g_timer_pwm_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        APP_ERR_PRINT("\r\n** R_GPT_Open API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Open Timer in One-Shot mode */
    err = R_GPT_Open(&g_timer_oneshot_ctrl, &g_timer_oneshot_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        gpt_deinit(&g_timer_pwm_ctrl);
        APP_ERR_PRINT("\r\n** R_GPT_Open API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable Start and Stop sources for Timer in PWM mode */
    err = R_GPT_Enable(&g_timer_pwm_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        gpt_deinit(&g_timer_pwm_ctrl);
        gpt_deinit(&g_timer_oneshot_ctrl);
        APP_ERR_PRINT("\r\n** R_GPT_Enable API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable Start source for Timer in One-Shot mode */
    err = R_GPT_Enable(&g_timer_oneshot_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        elc_deinit();
        gpt_deinit(&g_timer_pwm_ctrl);
        gpt_deinit(&g_timer_oneshot_ctrl);
        APP_ERR_PRINT("\r\n** R_GPT_Enable API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* On successful operations on ELC and GPT modules, user is asked enter any key as RTT input */
    APP_PRINT("\r\nEnter any key as RTT input. LED blinks for 5 seconds and stops");

    /* Wait until data is available in RTT */
    while (true)
    {
        if (APP_CHECK_DATA)
        {
            memset(&user_input[0], NULL_CHAR, BUFFER_SIZE_DOWN);
            APP_READ(user_input);
            err = R_ELC_SoftwareEventGenerate(&g_elc_ctrl, ELC_SOFTWARE_EVENT_0);
            if (FSP_SUCCESS != err)
            {
                elc_deinit();
                APP_ERR_PRINT("\r\n** R_ELC_SoftwareEventGenerate API failed **\r\n");
                APP_ERR_TRAP(err);
            }
            APP_PRINT("\r\nEnter any key as RTT input. LED blinks for 5 seconds and stops");
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at.
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

    /* Initialize the DDR settings */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins */
            R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @brief       This function closes opened ELC module before the project ends up in an Error Trap.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void elc_deinit (void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close ELC module */
    err = R_ELC_Close(&g_elc_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ELC Close failure message */
        APP_ERR_PRINT("** R_ELC_Close API failed **\r\n");
    }
}

/***********************************************************************************************************************
 * @brief       This function closes opened GPT module before the project ends up in an Error Trap.
 * @param[IN]   p_ctrl    Pointer to instance control.
 * @retval      None.
 **********************************************************************************************************************/
static void gpt_deinit (gpt_instance_ctrl_t * p_ctrl)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close GPT timer */
    err = R_GPT_Close(p_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* GPT Close failure message */
        APP_ERR_PRINT("** R_GPT_Close API failed **\r\n");
    }
}

/***********************************************************************************************************************
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process */

    /* Do not delete. Required to return to system_init */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_elc_ep)
 **********************************************************************************************************************/
