/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "xspi_qspi_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_xspi_qspi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

uint8_t g_src[DATA_SIZE];

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Open the QSPI instance */
    err = R_XSPI_QSPI_Open(&g_qspi_ctrl, &g_qspi_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* QSPI instance open failed */
        APP_PRINT("\r\nR_XSPI_QSPI_Open API failed\r\n");
        APP_ERR_TRAP(err);
    }

    /*---------- Chip Erase ----------*/
    /*
    err = R_XSPI_QSPI_Erase(&g_qspi_ctrl, (uint8_t *)QSPI_DEVICE_START_ADDRESS, SPI_FLASH_ERASE_SIZE_CHIP_ERASE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_Erase API for chip erase failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Chip erase successfully\r\n");
    }
    */

    /*---------- Sector Erase ----------*/
    uint8_t  * const p_erase_addr = (uint8_t *) QSPI_DEVICE_START_ADDRESS;
    uint32_t   const p_erase_len    = 4096U;
    err = R_XSPI_QSPI_Erase(&g_qspi_ctrl, p_erase_addr, p_erase_len);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_Erase API for sector erase failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Sector erase successful\r\n");
    }

    /* Wait for status register to update */
    spi_flash_status_t status_erase;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi_ctrl, &status_erase);
    } while (true == status_erase.write_in_progress);
    APP_PRINT("Erase done\r\n");

    /* Direct transfer (WRITE) */
    spi_flash_direct_transfer_t qspi_direct_transfer_write_enable = {0};
    qspi_direct_transfer_write_enable.command        = 0x06,  /* Write enable command */
    qspi_direct_transfer_write_enable.command_length = 1U,
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &qspi_direct_transfer_write_enable,
                                     SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer for write enable command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("R_XSPI_QSPI_DirectTransfer for write successful\r\n");
    }
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write =
    {
        .command        = 0x02U,  /* Page program command */
        .address        = 0x000234U,
        .data           = 0x12U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,
        .dummy_cycles   = 0U
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &qspi_test_direct_transfer_write,
                                     SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer for page program command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Page program command successful: addr=0x%08X len=%u data=0x%02X\r\n",
                  (unsigned) qspi_test_direct_transfer_write.address,
                  (unsigned) qspi_test_direct_transfer_write.data_length,
                  (unsigned) (qspi_test_direct_transfer_write.data & 0xFFU));
    }

    /* Wait for status register to update */
    spi_flash_status_t status_write;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /* Initialize write data */
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        g_src[i] = (uint8_t)i;
    }

    /* Write data via write API */
    /* xSPI1_CS0 memory, non-cache area use */
    uint8_t * p_dest = (uint8_t *)(QSPI_DEVICE_START_ADDRESS + WRITE_ADDRESS);
    err = R_XSPI_QSPI_Write(&g_qspi_ctrl, g_src, p_dest, DATA_SIZE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_Write API failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("R_XSPI_QSPI_Write API successful\r\n");
    }

    /* Wait for status register to update */
    spi_flash_status_t status_write2;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi_ctrl, &status_write2);
    } while (true == status_write2.write_in_progress);

    /* Enter Quad QPI mode */
    qspi_set_Quad_Mode_enable();
    APP_PRINT("qspi_set_Quad_Mode_enable successful\r\n");

    /* Direct transfer (READ) */
    spi_flash_direct_transfer_t qspi_test_direct_transfer_read =
    {
        .command        = 0xEBU,  /* Quad I/O Fast Read instruction */
        .address        = 0x000234U,
        .data           = 0U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,
        .dummy_cycles   = 6U /* 4READ instruction needs 6 dummy cycles */
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &qspi_test_direct_transfer_read, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for read command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Read command successful: cmd=0x%02X addr=0x%08X len=%u data=0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_read.command,
                    (unsigned) qspi_test_direct_transfer_read.address,
                    (unsigned) qspi_test_direct_transfer_read.data_length,
                    (unsigned) qspi_test_direct_transfer_read.data);
    }

    /* Verify written data equal to read data */
    if (qspi_test_direct_transfer_read.data != qspi_test_direct_transfer_write.data)
    {
        /* Exit Quad QPI mode */
        APP_ERR_PRINT("Written data and read data mismatch\r\n");
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    else
    {
        APP_PRINT("Written data and read data match\r\n");
    }

    /* Read data using memory-mapping mode */
    /* xSPI0_CS0 memory (Mirror area) */
    uint32_t read_buffer = *(uint8_t *)((uintptr_t)QSPI_DEVICE_START_ADDRESS +
            (uintptr_t)qspi_test_direct_transfer_write.address);
    APP_PRINT("Read data via memory-mapping mode addr=0x%08X data=0x%02X\r\n",
              (unsigned)qspi_test_direct_transfer_write.address, (unsigned) read_buffer);

    /* Verify written data equal read data */
    if (read_buffer != qspi_test_direct_transfer_write.data)
    {
        /* Exit Quad QPI mode */
        APP_ERR_PRINT("Written data and read data mismatch\r\n");
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    APP_PRINT("Written data and read data match\r\n");

    /* Verify written via write API */
    volatile uint8_t dummy_read;
    FSP_PARAMETER_NOT_USED(dummy_read);
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        uint8_t src_data = g_src[i];
        uint8_t dest_data = *(uint8_t *)((uintptr_t)QSPI_DEVICE_START_ADDRESS + (uintptr_t)WRITE_ADDRESS + (uintptr_t)i);
        if (src_data != dest_data)
        {
            APP_ERR_PRINT("Written data and read data mismatch\r\n");

            /* Exit Quad QPI mode */
            qspi_set_Quad_Mode_disable();
            APP_ERR_TRAP(FSP_ERR_ASSERTION);
        }

        /* If least significant 2 bits of dest_Data address are 0x02,
         * put dummy read sequence to deactivate unintentional Continuous Read mode */
        if ((i & 0x03) == 0x02)
        {
            dummy_read = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS + WRITE_ADDRESS);
        }
    }

    APP_PRINT("Verify written data match\r\n");

    /* Exit Quad QPI mode */
    qspi_set_Quad_Mode_disable();
    APP_PRINT("Exit Quad QPI mode\r\n");

    /* Close the application */
    APP_PRINT("XSPI_QSPI demo completed\r\n");
    while (1)
    {
        ;    /* Do nothing */
    }
}

/***********************************************************************************************************************
 * @brief     This function enables Quad Peripheral Interface (QPI) and switches the controller to the
              1S-4S-4S protocol.
 * @param[IN] None.
 * @return    None.
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_enable(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* For following settings, temporary set protocol 1S-1S-1S */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /* Read status register2(RDSR2) (35h) */
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for read status register command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Read status register command successful: cmd=0x%02X, len=%u\r\n",
                  (unsigned) direct_command_RDSR2.command,
                  (unsigned) direct_command_RDSR2.data_length);
    }

    uint32_t read_status = direct_command_RDSR2.data;

    /* Write enable (06h) */
    spi_flash_direct_transfer_t qspi_direct_transfer_write_enable = {0};
    qspi_direct_transfer_write_enable.command        = 0x06;
    qspi_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &qspi_direct_transfer_write_enable,
                                     SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for write enable command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Write enable command successful: cmd=0x%02X len=%u\r\n",
                  (unsigned) qspi_direct_transfer_write_enable.command,
                  (unsigned) qspi_direct_transfer_write_enable.command_length);
    }

    /* Write status register-2 (31h) (set QE bit 1) */
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = 0x02 | read_status;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;

     err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &direct_transfer_register_write,
                                      SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for write status register command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Write status register command successful: cmd=0x%02X len=%u\r\n",
                  (unsigned) direct_transfer_register_write.command,
                  (unsigned) direct_transfer_register_write.command_length);
    }

    /* Wait for status register to update */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /* 1S-4S-4S protocol setting */
    err = R_XSPI_QSPI_SpiProtocolSet(&g_qspi_ctrl, SPI_FLASH_PROTOCOL_1S_4S_4S);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_SpiProtocolSet API for 1S-4S-4S protocol failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("R_XSPI_QSPI_SpiProtocolSet API for 1S-4S-4S protocol successful\r\n");
    }
}

/***********************************************************************************************************************
 * @brief     This function disables QPI mode and restores single-I/O SPI (1S-1S-1S) protocol.
 * @param[IN] None.
 * @return    None.
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_disable(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* 1S-1S-1S protocol setting */
    err = R_XSPI_QSPI_SpiProtocolSet(&g_qspi_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_SpiProtocolSet API for 1S-1S-1S protocol failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("R_XSPI_QSPI_SpiProtocolSet API for 1S-1S-1S protocol successful\r\n");
    }

    /* Read status register2(RDSR2) (35h) */
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for read status register command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Read status register command successful: cmd=0x%02X, len=%u\r\n",
                  (unsigned) direct_command_RDSR2.command,
                  (unsigned) direct_command_RDSR2.data_length);
    }

    uint32_t read_status = direct_command_RDSR2.data;

    /* Write enable (06h) */
    spi_flash_direct_transfer_t qspi_direct_transfer_write_enable = {0};
    qspi_direct_transfer_write_enable.command        = 0x06;
    qspi_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &qspi_direct_transfer_write_enable,
                                     SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for write enable command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Write enable command successful: cmd=0x%02X len=%u\r\n",
                  (unsigned) qspi_direct_transfer_write_enable.command,
                  (unsigned) qspi_direct_transfer_write_enable.command_length);
    }

    /* Write status register-2 (31h) (set QE bit 1) */
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = read_status & 0xfd;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;

     err = R_XSPI_QSPI_DirectTransfer(&g_qspi_ctrl, &direct_transfer_register_write,
                                      SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_XSPI_QSPI_DirectTransfer API for write status register command failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("Write status register command successful: cmd=0x%02X\r\n",
                  (unsigned) direct_transfer_register_write.command);
    }

    /* Wait for status register to update */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi_ctrl, &status_write);
    } while (true == status_write.write_in_progress);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins */
            R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process */

    /* Do not delete. Required to return to system_init */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_xspi_qspi_ep)
 **********************************************************************************************************************/
