/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "i2c_pmic.h"
#include "common_utils.h"
#include "timer_pwm.h"
#include "uart_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_scif_uart_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
        version.version_id_b.patch);

    APP_PRINT(EP_INFO);

    /* Initialize GTM in Periodic mode */
    err = gtm_initialize();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("\r\n** gtm_initialize failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Start GTM */
    err = gtm_start();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("\r\n** gtm_start failed **\r\n");
        timer_gtm_deinit();
        APP_ERR_TRAP(err);
    }

    /* Initialize UART */
    err = uart_initialize();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("\r\n** uart_initialize failed **\r\n");
        timer_gtm_deinit();
        APP_ERR_TRAP(err);
    }

    /* User defined function to demonstrate UART functionality */
    err = uart_ep_demo();
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("\r\n** uart_ep_demo failed **\r\n");
        timer_gtm_deinit();
        deinit_uart();
        APP_ERR_TRAP(err);
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* Allow access to IP beyond AXI */
        pd_all_on_postproc_axi();
        pd_all_on_postproc();
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_scif_uart_ep)
 **********************************************************************************************************************/
