/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "r_usb_pcdc_apl.h"

/***********************************************************************************************************************
 * @addtogroup usb_pcdc_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

uint8_t  g_buf[DATA_LEN+4];

usb_pcdc_linecoding_t g_line_coding;

void handle_error(fsp_err_t err, char *err_str);

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @fn         hal_entry
 * @brief      hal_entry function.
 * @retval     None
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    uint8_t  rtt_buffer[DATA_LEN]             =  {NULL_CHAR};

    fsp_pack_version_t  version               =  {RESET_VALUE};
    
    usb_status_t     event;

    usb_event_info_t event_info;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    
    /* Print the EP information on the RTT viewer */
    APP_PRINT (EP_INFO);

    err = g_usb_on_usb.open(&g_basic0_ctrl, &g_basic0_cfg);

    /* Error Handle */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nError in initializing USB Host CDC\r\n");
        APP_ERR_TRAP (err);
    }

    while (1)
    {
        /* Get USB event data */
        err = g_usb_on_usb.eventGet(&event_info, &event);

        /* Error Handle */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT ("\r\nError in get events USB Host CDC\r\n");
            APP_ERR_TRAP (err);
        }

        /* Handle the received event (if any) */
        switch (event)
        {
            case USB_STATUS_CONFIGURED:
            case USB_STATUS_WRITE_COMPLETE:

                /* Initialization complete; get data from host */
                err = g_usb_on_usb.read(&g_basic0_ctrl, g_buf, DATA_LEN, USB_CLASS_PCDC);

                /* Handle Error */
                if (FSP_SUCCESS != err)
                {
                    handle_error (err,"**R_USB_Read API FAILED**");
                }

                break;
            case USB_STATUS_READ_COMPLETE:

                /* Loop back received data to host */
                err = g_usb_on_usb.write(&g_basic0_ctrl, g_buf, event_info.data_size, USB_CLASS_PCDC);

                /* Handle Error */
                if (FSP_SUCCESS != err)
                {
                    handle_error (err, "**R_USB_Write API FAILED**");
                }

                memcpy(rtt_buffer, g_buf, event_info.data_size);
                APP_PRINT("%s" , rtt_buffer);
                memset(rtt_buffer, NULL_CHAR, DATA_LEN);
                break;
            case USB_STATUS_REQUEST:   /* Receive Class Request */
                if (USB_PCDC_SET_LINE_CODING == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* Configure virtual UART settings */
                    err = g_usb_on_usb.periControlDataGet(&g_basic0_ctrl, (uint8_t *) &g_line_coding, LINE_CODING_LENGTH);

                    /* Error Handle */
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT ("\r\n**R_USB_PeriControlDataGet API FAILED**\r\n");
                        APP_ERR_TRAP (err);
                    }
                }
                else if (USB_PCDC_GET_LINE_CODING == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* Send virtual UART settings back to host */
                    err = g_usb_on_usb.periControlDataSet(&g_basic0_ctrl, (uint8_t *) &g_line_coding, LINE_CODING_LENGTH);

                    /* Error Handle */
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT ("\r\n**R_USB_PeriControlDataSet API FAILED**\r\n");
                        APP_ERR_TRAP (err);
                    }
                }
                else
                {
                    /* ACK all other status requests */
                    err = g_usb_on_usb.periControlStatusSet(&g_basic0_ctrl, USB_SETUP_STATUS_ACK);

                    /* Error Handle */
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT ("\r\n**R_USB_PeriControlStatusSet API FAILED**\r\n");
                        APP_ERR_TRAP (err);
                    }
                }
                break;
            case USB_STATUS_SUSPEND:
            case USB_STATUS_DETACH:
                {
                break;
                }

            default:
                break;
        }
    }
}
/***********************************************************************************************************************
 * End of function: hal_entry
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */;
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
/***********************************************************************************************************************
 * End of function: R_BSP_WarmStart
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @fn     handle_error 
 * @brief  This function is called to do closing of usb module using its HAL level API and handles the error trap.
 *  Handle the Error internally with Proper Message. Application handles the rest.
 * @param[IN] err       Return values of APIs
 * @param[IN] err_str   Print message from the failed API call
 * @retval    None
 **********************************************************************************************************************/
void handle_error(fsp_err_t err, char *err_str)
{
    fsp_err_t error = FSP_SUCCESS;

    /* close opened USB module */
    error = R_USB_Close(&g_basic0_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != error)
    {
        APP_ERR_PRINT ("**\r\n R_USB_Close API FAILED **\r\n");
    }
    APP_ERR_PRINT(err_str);
    APP_ERR_TRAP(err);
}
/***********************************************************************************************************************
 * End of function handle_error
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @} (end addtogroup usb_pcdc_ep)
 **********************************************************************************************************************/
