/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "icu_inter_cpu_irq_ep.h"

extern bsp_leds_t g_bsp_leds;

/***********************************************************************************************************************
 * @addtogroup icu_inter_cpu_irq_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version =   { RESET_VALUE };

    /* Get the FSP version */
    R_FSP_VersionGet (&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);

    /* Print the EP information on the RTT viewer */
    APP_PRINT (EP_INFO);

    /* Initialize ICU_INTER_CPU_IRQ driver */
    err = R_ICU_INTER_CPU_IRQ_Open (&g_icu_inter_cpu_irq_ctrl, &g_icu_inter_cpu_irq_cfg);

    if (FSP_SUCCESS != err)
    {   /* ICU_INTER_CPU_IRQ module init failed */
        APP_PRINT("\r\n ** ICU_INTER_CPU_IRQ INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\r\nICU_INTER_CPU_IRQ starts generating software interrupt and then toggling on-board LED.\r\n");

    /* Main loop */
    while (true)
    {
        err = R_ICU_INTER_CPU_IRQ_Generate(&g_icu_inter_cpu_irq_ctrl);

        if (FSP_SUCCESS != err)
        {   /* ICU_INTER_CPU_IRQ module generate interrupt failed */
            APP_PRINT("\r\n ** ICU_INTER_CPU_IRQ GENERATES INTERRUPT FAILED ** \r\n");
            APP_ERR_TRAP(err);
        }

        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/***********************************************************************************************************************
 * @brief      User defined icu_inter_cpu_irq callback.
 * @param[IN]  p_args  Callback arguments from the Inter-CPU IRQ on ICU driver.
 * @retval     None
 **********************************************************************************************************************/
void icu_inter_cpu_callback(icu_inter_cpu_irq_callback_args_t * p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* If this board has no LEDs then trap here */
    if (0 == leds.led_count)
    {
        while (1)
        {
            ;                          // There are no LEDs on this board
        }
    }

    /* Toggle board LEDs */
    for (uint32_t i = 0; i < leds.led_count; i++)
    {
        R_BSP_PinToggle ((bsp_io_region_t) leds.p_leds[i][1], (bsp_io_port_pin_t) leds.p_leds[i][0]);
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup icu_inter_cpu_irq_ep)
 **********************************************************************************************************************/
