/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/

#include "common_utils.h"
#include "timer_setup.h"
#include "ext_irq_setup.h"

/*******************************************************************************************************************//**
 * @addtogroup r_wdt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/* External global variables */
/* LED structure used to blink on board LED */
extern bsp_leds_t g_bsp_leds;
extern volatile uint8_t g_timer_overflow_counter;

/* Private function declarations */
/* Private function declarations */
/* Function used to read J-Link RTT Viewer input and proceed */
static fsp_err_t read_Input_from_RTTViewer (void);

/* Function used to enable WDT in debug mode */
static void enable_wdt_count_in_debug_mode (void);

/* Function used to check if reset is caused by WDT or not */
static void check_reset_status (void);

/*******************************************************************************************************************//**
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT("\r\nThis example project demonstrates the typical use of the WDT HAL module APIs\r\n");
    APP_PRINT("User input initializes the WDT and start GTM timer\r\n");
    APP_PRINT("WDT counter is refreshed periodically every 1 second when the GTM timer expires\r\n");
    APP_PRINT("On pressing the Push button, the WDT reset will issued\r\n");

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == g_bsp_leds.led_count)
    {
        APP_PRINT("No on-board LEDs Found\r\n");
        APP_ERR_TRAP(FSP_ERR_UNSUPPORTED);
    }

    check_reset_status();

    /* Initialize GTM in Periodic Mode */
    err = init_gtm_module();
    if (FSP_SUCCESS != err)
    {
        /* Timer init failed */
        APP_ERR_PRINT(" ** init_gtm_module failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initialize External IRQ */
    err = init_irq_module();
    if (FSP_SUCCESS != err)
    {
        /* External IRQ init failed, cleanup the timer initialization */
        APP_ERR_PRINT("** init_irq_module failed **\r\n");
        deinit_gtm_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for User Selection */
    APP_PRINT("\r\nEnter 1 to Enable WDT\r\n");
    APP_PRINT("\r\nUser Input:\r\n");

    while (true)
    {
        /* Process input only when User has provided one */
        if (APP_CHECK_DATA)
        {
            err = read_Input_from_RTTViewer();
            if (FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ module */
                deinit_gtm_module();
                deinit_irq_module();
                APP_ERR_TRAP(err);
            }
        }

        /* For every 3Sec. J-Link RTT Viewer prints WDT refresh message.
         * This is done to avoid the continuous print message on J-Link RTT Viewer */
        if (WDT_REFRESH_COUNTER_VALUE == g_timer_overflow_counter)
        {
            g_timer_overflow_counter = RESET_VALUE;
            APP_PRINT("WDT counter Refreshed.\r\n");
        }
    }
}

/*******************************************************************************************************************//**
 * @brief       This function reads user input from J-Link RTT Viewer. Handle the Error internally with Proper Message.
 *              Application handles the rest.
 * @param[IN]   None.
 * @retval      Any other error code apart from FSP_SUCCESS  unsuccessful to perform operation.
 **********************************************************************************************************************/
fsp_err_t read_Input_from_RTTViewer(void)
{
	/* Error status */
    fsp_err_t err = FSP_SUCCESS;

    /* Variable to store user input */
    uint8_t rByte[BUFFER_SIZE] = { RESET_VALUE };
    uint8_t user_data = RESET_VALUE;

    /* Read First byte of data provided by user */
    APP_READ(rByte);

    /* Conversion user data to integer value */
    user_data = (uint8_t)atoi((char *)&rByte);

    switch (user_data)
    {
        case ENABLE_WDT:
        {
            /* Enable WDT to count and generate NMI or Reset when the debugger(J-Link) is connected. */
            enable_wdt_count_in_debug_mode();

            /* Open WDT. For every GTM timeout, WDT will get refreshed. */
            err = R_WDT_Open(&g_wdt_ctrl, &g_wdt_cfg);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_WDT_Open API Failed **\r\n");
                return err;
            }

            /* Start GTM timer in Periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** timer_start failed **\r\n");
                return err;
            }

            /* Enable External IRQ */
            err = enable_irq_module();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** enable_irq_module failed **\r\n");
                return err;
            }

            /* Print message to indicate user about application status. */
            APP_PRINT("WDT initialized, GTM Timer Started\r\n");
            APP_PRINT("To stop WDT counter from refreshing, press the push button\r\n");
            break;
        }
        default:
        {
            /* Menu for User Selection */
            APP_PRINT("Invalid Input\r\n");
            APP_PRINT("Please provide input from below option\r\n");
            APP_PRINT("Enter 1 to Enable WDT\r\n");
            APP_PRINT("User Input:\r\n");
            break;
        }
    }
    user_data = RESET_VALUE;
    return err;
}

/*******************************************************************************************************************//**
 * @brief       This function is called to enable WDT counter in debug mode.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void enable_wdt_count_in_debug_mode(void)
{
    /* Clear this bit to Stop WDT2 from counting in debug mode */
    R_SYSC->SYS_WDT2_CTRL_b.WDTSTOPMASK = RESET_VALUE;
}

/*******************************************************************************************************************//**
 * @brief       This function is called to check whether reset is caused by WDT.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    /* Check if reset was caused by the WDT? If it was, turn on LED to indicate WDT reset triggered. */
    if (R_CPG_CPG_WDTOVF_RST_WDTOVF2 == R_CPG->CPG_WDTOVF_RST_b.WDTOVF2)
    {
        /* Clear the flag once read the value */
        R_CPG->CPG_WDTOVF_RST = R_CPG_CPG_WDTOVF_RST_WDTOVF2_Msk | R_CPG_CPG_WDTOVF_RST_WDTOVF2_WEN_Msk;

        /* Turn ON LED */
        /* Here is the place to add operations in accordance with User System.
         * In this sample, LED blink and debug message output operations are implemented. */

        /* If System Reset is enabled in the FSP configurator for the WDT stack,
         * this EP will not run because the DDR SDRAM resets as well.
         * Please adapt the behavior according to your system requirements. */
        R_BSP_PinWrite((bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_HIGH);

        APP_PRINT("\r\n************************ WDT Reset detected ************************\r\n");
    }
    else
    {
        /* Do Nothing */
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[IN]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/*******************************************************************************************************************//**
 * @} (end addtogroup r_wdt_ep)
 **********************************************************************************************************************/
