/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "xspi_qspi_xip_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_xspi_qspi_xip_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

extern void LED_blinky (void);

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);
    
    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    err = R_XSPI_QSPI_Open(&g_qspi0_ctrl, &g_qspi0_cfg);
    if (FSP_SUCCESS != err)
    {   /* QSPI instance open failed */
        APP_PRINT("\r\n ** R_XSPI_QSPI OPEN FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Enter QPI mode */
    qspi_set_Quad_Mode_enable();
    APP_PRINT("[ENTER] QPI enabled\r\n");

    /* Enter XiP mode */
    err = R_XSPI_QSPI_XipEnter(&g_qspi0_ctrl);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[XIP] enter failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    APP_PRINT("[XIP] entered\r\n");

    /* Blink 10 times (Executed from serial Flash) */
    LED_blinky();
    APP_PRINT("[LED] done\r\n");

    /* Exit XiP mode */
    err = R_XSPI_QSPI_XipExit(&g_qspi0_ctrl);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[XIP] exit failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    APP_PRINT("[XIP] exited\r\n");

    /* Exit QPI mode */
    qspi_set_Quad_Mode_disable();
    APP_PRINT("[EXIT] QPI disabled\r\n");

    /* Close the application */
    APP_PRINT("[DONE]\r\n");
    while (1)
    {
        ;    /* Do nothing */
    }
}

/***********************************************************************************************************************
 * @brief     Enable Quad Peripheral Interface (QPI) and switch the controller to the 1S-4S-4S protocol.
 * @param[in] None
 * @return    None
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_enable(void)
{
    /* For following settings, temporary set protocol 1S-1S-1S */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*---------------- Read status register2(RDSR2) (35h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;
    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR2.command,
                    (unsigned) direct_command_RDSR2.data_length,
                    (unsigned) (direct_command_RDSR2.data & 0xFFU));    /* cast to unsigned */
    }

    uint32_t read_status2 = direct_command_RDSR2.data;

    /*---------------- Write enable (06h)----------------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06;
    qspi_test_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /*---------------- Write Status Register-2 (31h) (set Quad Enable (QE) bit = 1) ----------------*/
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = 0x02 | read_status2;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_transfer_register_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_transfer_register_write.command,
                    (unsigned) direct_transfer_register_write.data_length,
                    (unsigned) (direct_transfer_register_write.data & 0xFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void) R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /* 1S-4S-4S protocol settings. */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_4S_4S);
}

/***********************************************************************************************************************
 * @brief     Disable QPI mode and restore single-I/O SPI (1S-1S-1S) protocol.
 * @param[in] None
 * @return    None
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_disable(void)
{
    /* 1S-1S-1S protocol settings. */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*---------------- Read status register2(RDSR2) (35h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;
    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR2.command,
                    (unsigned) direct_command_RDSR2.data_length,
                    (unsigned) (direct_command_RDSR2.data & 0xFFU));    /* cast to unsigned */
    }
    uint32_t read_status = direct_command_RDSR2.data;

    /*---------------- Write enable (06h) ----------------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06;
    qspi_test_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);

    /*---------------- Write Status Register-2 (31h) (set Quad Enable (QE) bit = 0) ----------------*/
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = read_status & 0xfd;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_transfer_register_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_transfer_register_write.command,
                    (unsigned) direct_transfer_register_write.data_length,
                    (unsigned) (direct_transfer_register_write.data & 0xFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void) R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_xspi_qspi_xip_ep)
 **********************************************************************************************************************/
