/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "mipi_dsi_ep.h"
#include "r_mipi_dsi_b.h"
#include "common_utils.h"

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/***********************************************************************************************************************
 * @addtogroup r_mipi_dsi_ep
 * @{
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    mipi_dsi_entry();
}

/***********************************************************************************************************************
 * @brief      This function is used initialize related module and start display operation.
 * @param[in]  None.
 * @retval     None.
 **********************************************************************************************************************/
void mipi_dsi_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);
    APP_PRINT(MIPI_DSI_MENU);

    /* Open LCDC module */
    err = R_LCDC_Open (g_display.p_ctrl, g_display.p_cfg);
    handle_error(err, "** LCDC Open API failed **\r\n");

    /* MIPI-DSI setting */
    R_MIPI_DSI_B_Open(g_mipi_dsi0.p_ctrl, g_mipi_dsi0.p_cfg);

    /* Initialize GTM module */
    err = R_GTM_Open(&g_timer0_ctrl, &g_timer0_cfg);

    /* Handle error */
    handle_error(err, "** R_GTM Open API failed **\r\n");

    /* Initialize RIIC MASTER module */
    err = R_RIIC_MASTER_Open(&g_i2c_master_ctrl, &g_i2c_master_cfg);

    /* Handle error */
    handle_error(err, "** RIIC MASTER Open API failed **\r\n");

    /* Initialize LCD. */
    mipi_dsi_push_table(g_lcd_init_focuslcd);

    /* Start the MIPI_DSI */
    R_MIPI_DSI_B_Start(g_mipi_dsi0.p_ctrl);

    /* Initialize INTC_IRQ module */
    err = R_INTC_IRQ_ExternalIrqOpen(&g_external_irq_ctrl, &g_external_irq_cfg);

    /* Handle error */
    handle_error(err, "** INTC_IRQ Open API failed **\r\n");

    /* Start display 8-color bars */
    mipi_dsi_start_display();
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open(&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_mipi_dsi_ep)
 **********************************************************************************************************************/
