/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "poeg_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_poeg_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/* Global variables */
uint8_t                 g_num_bytes                     = RESET_VALUE;
static volatile uint8_t g_interrupt_pin_trigger_flag    = RESET_VALUE;
static volatile uint8_t g_interrupt_output_level_flag   = RESET_VALUE;
static volatile uint8_t g_mode_flag                     = RESET_VALUE;

/* Board specific pin configuration */
#define POEG_TEST_CONTROL_PIN                           (BSP_IO_PORT_06_PIN_05)

/* User defined function */
static void led_pin_initialisation(void);

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry (void)
{
    fsp_err_t          err     = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Initialize of LED Pins */
    led_pin_initialisation();

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize the POEG0 */
    err = init_poeg0_module();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\ninit_poeg0_module function failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\nPOEG0 initialized successfully for GPT output level mode\r\n");
    }

    /* Initialize the POEG3 */
    err = init_poeg3_module();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\ninit_poeg3_module function failed\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("POEG3 initialized successfully for GTETRG pin trigger and software API\r\n");
    }

    /* Initialize the Timer0 in PWM mode */
    err = init_gpt_timer_pwm0();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\ninit_gpt_timer_pwm0 function failed\r\n");

        /* Close PWM Timer instance */
        deinit_gpt_timer(&g_timer_pwm0_ctrl);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("GPT Timer0 initialized successfully for PWM mode\r\n");
    }

    /* Initialize the Timer5 in PWM mode */
    err = init_gpt_timer_pwm5();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\ninit_gpt_timer_pwm5 function failed\r\n");

        /* Close PWM Timer instance */
        deinit_gpt_timer(&g_timer_pwm5_ctrl);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("GPT Timer5 initialized successfully for PWM mode\r\n");
    }

    while (true)
    {
        APP_PRINT(MENU_INFO);

        /* Process input only when user has provided one */
        while (!APP_CHECK_DATA)
        {
            ; /* Wait user input */
        }
        if (APP_CHECK_DATA)
        {
            poeg_output_disable_and_reset_options();
        }
    }
}

/***********************************************************************************************************************
 * @brief     This function reads the command (input) for RTT and processes the command for POEG output disable.
 * @param[in] None.
 * @retval    FSP_SUCCESS                  Upon successful.
 * @retval    Any other error code apart from FSP_SUCCESS Upon Unsuccessful.
 **********************************************************************************************************************/
fsp_err_t poeg_output_disable_and_reset_options(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Variables to store user input */
    uint8_t rByte[BUFFER_SIZE_DOWN] = {NULL_CHAR};
    uint8_t converted_rtt_input     = RESET_VALUE;

    APP_READ(rByte);

    /* User input selection */
    converted_rtt_input = (uint8_t)atoi((char *)rByte);

    switch (converted_rtt_input)
    {
        /* POEG_TRIGGER_ON_GTETRG_INPUT_PIN_LEVEL - Disables GPT output pins based
         * on GTETRG input pin level. */
        case POEG_TRIGGER_ON_GTETRG_INPUT_PIN_LEVEL:
        {
            /* Start PWM Timer5 */
            err = R_GPT_Start(&g_timer_pwm5_ctrl);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT ("\r\nR_GPT_Start API failed\r\n");
                return(err);
            }
            else
            {
                APP_PRINT("\r\nStarted Timer5 in PWM Mode\r\n");
            }
            APP_PRINT("Enter any key to disable GPT output using GTETRG trigger pin mode\r\n");
            while (true)
            {
                if (APP_CHECK_DATA)
                {
                    APP_READ(rByte);
                    break;
                }
            }
            g_mode_flag = POEG_TRIGGER_ON_GTETRG_INPUT_PIN_LEVEL;

            /* Set GTETRG to trigger POEG */
            R_IOPORT_PinWrite(&g_ioport_ctrl, POEG_TEST_CONTROL_PIN, BSP_IO_LEVEL_LOW);

            /* Enable IRQ */
            R_BSP_IrqEnable(POEG_GROUP3_IRQn);
            while (!g_interrupt_pin_trigger_flag)
            {
                /* Wait for interrupt flag */
            }
            APP_PRINT("\r\nPOEG trigger on GTETRG input pin level successful\r\n");
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG3, BSP_IO_LEVEL_HIGH);

            /* GTETRG inactive */
            R_IOPORT_PinWrite(&g_ioport_ctrl,POEG_TEST_CONTROL_PIN, BSP_IO_LEVEL_HIGH);
            break;
        }

        /* POEG_OUTPUT_DISABLE_SOFTWARE_API - Disable GPT output pins using POEG software API */
        case POEG_OUTPUT_DISABLE_SOFTWARE_API:
        {
            /* Start PWM Timer5 */
            err = R_GPT_Start(&g_timer_pwm5_ctrl);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT ("\r\nR_GPT_Start API failed\r\n");
                return(err);
            }
            else
            {
                APP_PRINT("\r\nStarted Timer5 in PWM Mode\r\n");
            }

            APP_PRINT("Enter any key to disable GPT output pins using POEG software API\r\n");
            while (true)
            {
                if (APP_CHECK_DATA)
                {
                    APP_READ(rByte);

                    /* Disable POEG3 GPT output pins using POEG software API */
                    err = R_POEG_OutputDisable(&g_poeg3_ctrl);
                    break;
                }
            }

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\nR_POEG_OutputDisable API failed\r\n");
            }
            APP_PRINT("\r\nPOEG output disable using software API successful\r\n");
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG3, BSP_IO_LEVEL_HIGH);
            break;
        }

        /* POEG_OUTPUT_DISABLE_REQUEST_FROM_GPT - Disables GPT using output-disable
         * request from the GPT. */
        case POEG_OUTPUT_DISABLE_REQUEST_FROM_GPT:
        {
            /* Start PWM Timer0 */
            err = R_GPT_Start(&g_timer_pwm0_ctrl);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT ("\r\nR_GPT_Start API failed\r\n");
                return(err);
            }
            else
            {
                APP_PRINT("\r\nStarted Timer0 in PWM Mode\r\n");
            }
            APP_PRINT("\r\nEnter any key to disable GPT Timer0 output\r\n");
            while (true)
            {
                if (APP_CHECK_DATA)
                {
                    APP_READ(rByte);
                    break;
                }
            }
            g_mode_flag     = POEG_OUTPUT_DISABLE_REQUEST_FROM_GPT;

            /* Enable same time output level disable request */
            R_GPT0->GTINTAD_b.GRPABH = 1;
            R_GPT0->GTINTAD_b.GRPABL = 1;

            APP_PRINT("\r\nPOEG output disable on GPT output level successful\r\n");
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG0, BSP_IO_LEVEL_HIGH);

            /* Disable same time output level disable request */
            R_GPT0->GTINTAD_b.GRPABH = 0;
            R_GPT0->GTINTAD_b.GRPABL = 0;
            break;
        }

        /* POEG_RESET - Reset the POEG status */
        case POEG_RESET:
        {
            err = reset_poeg_module();

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\nFailed to reset POEG with error code: 0x%x",err);
            }
            break;
        }
        default:
        {
            APP_PRINT("\r\nInvalid input, Please enter the value between 1-4\r\n");
            break;
        }
    }
    return err;
}

/***********************************************************************************************************************
 * @brief       This function is used for POEG channel 0 callback to disable the IRQ and set the mode flags.
 * @param[in]   p_arg   POEG callback argument.
 * @return      None.
 **********************************************************************************************************************/
void channel0_user_callback(poeg_callback_args_t * p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    if (POEG_OUTPUT_DISABLE_REQUEST_FROM_GPT == g_mode_flag)
    {
        APP_PRINT("\r\nInterrupt occured in GPT OUTPUT LEVEL Mode\r\n");
        g_interrupt_output_level_flag = SET_FLAG;
    }

    /* If the POEG0 cannot be reset, disable the POEG0 interrupt to prevent
     * it from firing continuously. */
    R_BSP_IrqDisable(POEG_GROUP0_IRQn);
}

/***********************************************************************************************************************
 * @brief       This function is used for POEG channel 3 callback to disable the IRQ and set the mode flag.
 * @param[in]   p_arg   POEG callback argument.
 * @return      None.
 **********************************************************************************************************************/
void channel3_user_callback(poeg_callback_args_t * p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    if (POEG_TRIGGER_ON_GTETRG_INPUT_PIN_LEVEL == g_mode_flag)
    {
        APP_PRINT("\r\nInterrupt occured in Pin Trigger Mode\r\n");
        g_interrupt_pin_trigger_flag = SET_FLAG;
    }

    /* If the POEG3 cannot be reset, disable the POEG3 interrupt to prevent
     * it from firing continuously. */
    R_BSP_IrqDisable(POEG_GROUP3_IRQn);
}

/***********************************************************************************************************************
 * @brief       This function resets POEG module.
 * @param[in]   None.
 * @retval      FSP_SUCCESS                  Upon successful POEG Reset.
 * @retval      Any other error code apart from FSP_SUCCESS Upon Unsuccessful.
 **********************************************************************************************************************/
fsp_err_t reset_poeg_module(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Variables to store user input */
    uint8_t rByte[BUFFER_SIZE_DOWN] = {NULL_CHAR};
    uint8_t converted_rtt_input     = RESET_VALUE;

    APP_PRINT(RESET_MENU_INFO);

    /* Process input only when user has provided one */
    while (!APP_CHECK_DATA)
    {
        ; /* Wait user input */
    }
    if (APP_CHECK_DATA)
    {
        APP_READ(rByte);
        converted_rtt_input = (uint8_t)atoi((char *)rByte);
    }
    switch (converted_rtt_input)
    {
        case POEG_CHANNEL_0:
        {
            /* Invert GTIOCB and apply it to GTIOCA */
            uint32_t gtiob          = g_timer_pwm0_ctrl.p_reg->GTIOR_b.GTIOB;
            uint32_t inverted_gtiob = (~gtiob) & R_GPT0_GTIOR_GTIOA_Msk;

            /* Apply the inverted configuration safely */
            g_timer_pwm0_ctrl.p_reg->GTIOR_b.GTIOA = (uint8_t)(inverted_gtiob & R_GPT0_GTIOR_GTIOA_Msk);

            /* GTIOR changes take effect after the next cycle end */
            while (g_timer_pwm0_ctrl.p_reg->GTCNT < g_timer_pwm0_cfg.period_counts - 1)
            {
                ;
            }

            do
            {
                err = R_POEG_Reset(&g_poeg0_ctrl);
            } while (FSP_SUCCESS != err);

            APP_PRINT("\r\nReset POEG 0 successful\r\n");
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG0, BSP_IO_LEVEL_LOW);
            g_interrupt_output_level_flag = CLEAR_FLAG;
            break;
        }

        case POEG_CHANNEL_3:
        {
            /* Invert GTIOCB and apply it to GTIOCA */
            uint32_t gtiob = g_timer_pwm5_ctrl.p_reg->GTIOR_b.GTIOB;
            uint32_t inverted_gtiob = (~gtiob) & R_GPT0_GTIOR_GTIOA_Msk;

            /* Apply the inverted configuration safely */
            g_timer_pwm5_ctrl.p_reg->GTIOR_b.GTIOA = (uint8_t)(inverted_gtiob & R_GPT0_GTIOR_GTIOA_Msk);

            /* GTIOR changes take effect after the next cycle end */
            while (g_timer_pwm5_ctrl.p_reg->GTCNT < g_timer_pwm5_cfg.period_counts - 1)
            {
                ;
            }

            do
            {
                err = R_POEG_Reset(&g_poeg3_ctrl);
            } while (FSP_SUCCESS != err);

            APP_PRINT("\r\nReset POEG 3 successful\r\n");
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG3, BSP_IO_LEVEL_LOW);
            g_interrupt_pin_trigger_flag = CLEAR_FLAG;
            break;
        }

        default:
        {
            APP_PRINT("\r\nInvalid input, Please enter the value between 1-2\r\n");
            break;
        }
    }
    return err;
}

/***********************************************************************************************************************
 * @brief       This function initializes state of LED pins.
 * @param[in]   None.
 * @return      None.
 **********************************************************************************************************************/
static void led_pin_initialisation(void)
{
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG0, BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN_POEG3, BSP_IO_LEVEL_LOW);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_poeg_ep)
 **********************************************************************************************************************/
