/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "i2c_pmic.h"
#include "common_utils.h"
#include "timer_setup.h"
#include "ext_irq_setup.h"

/***********************************************************************************************************************
 * @addtogroup r_wdt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/* External global variables */
/* LED Structure used to blink on board LED */
extern bsp_leds_t g_bsp_leds;
extern volatile uint8_t g_timer_overflow_counter;

/* Private function declarations */
/* Function used to read J-Link RTT Viewer input and proceed */
static fsp_err_t read_Input_from_RTTViewer(void);

/* Function used to enable WDT in debug mode */
static void enable_wdt_count_in_debug_mode(void);

/* Function used to check if reset is caused by WDT or not */
static void check_reset_status(void);

/* User-level callback invoked by the WDT driver ISR */
void wdt_user_callback(wdt_callback_args_t * const p_unused);

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t          err     = FSP_SUCCESS;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == g_bsp_leds.led_count)
    {
        APP_PRINT("No on-board LEDs Found\r\n");
        APP_ERR_TRAP(FSP_ERR_UNSUPPORTED);
    }

    check_reset_status();

    /* Initializing GTM in Periodic Mode */
    err = init_gtm_module();
    if (FSP_SUCCESS != err)
    {
        /* Timer init failed */
        APP_ERR_PRINT("** init_gtm_module failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initializing external IRQ */
    err = init_irq_module();
    if (FSP_SUCCESS != err)
    {
        /* External IRQ init failed, cleanup the timer initialization */
        APP_ERR_PRINT("** init_irq_module failed **\r\n");
        deinit_gtm_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for user selection */
    APP_PRINT("\r\nEnter 1 to Enable WDT\r\n");
    APP_PRINT("\r\nUser Input:\r\n");

    while (true)
    {
        /* Process input only when User has provided one */
        if (APP_CHECK_DATA)
        {
            err = read_Input_from_RTTViewer();
            if (FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ module */
                deinit_gtm_module();
                deinit_irq_module();
                APP_ERR_TRAP(err);
            }
        }

        /* For every 3 seconds. J-Link RTT Viewer prints WDT refresh message.
         * This is done to avoid the continuous print message on J-Link RTT Viewer */
        if (WDT_REFRESH_COUNTER_VALUE == g_timer_overflow_counter)
        {
            g_timer_overflow_counter = RESET_VALUE;
            APP_PRINT("WDT counter refreshed.\r\n");
        }
    }
}

/***********************************************************************************************************************
 * @brief     This function clears any pending ICU Error_CM33 flags so they will not re-trigger.
 * @param[in] p_unused    Unused callback argument (required by prototype).
 * @retval    None.
 **********************************************************************************************************************/
void wdt_user_callback(wdt_callback_args_t * const p_unused)
{
    /* Cast to void to indicate the parameter is unused */
    FSP_PARAMETER_NOT_USED(p_unused);

    /* If a bus-error flag is set, clear it to avoid repeated interrupts */
    if (1 == R_INTC->ERINTM33CTL0_b.ERRM30STAT0)
    {
        R_INTC->BECLR0 = 0xFFFFFFFF;
    }

    /* If the WDT underflow flag is set, clear it to avoid re-entry */
    if (1 == R_INTC->ERINTM33CTL0_b.ERRM30STAT31)
    {
        R_INTC->ERINTM33CLR0_b.ERRM30CLR29 = 1U;
    }
}

/***********************************************************************************************************************
 * @brief       This function reads user input from J-Link RTT Viewer, handles the error internally with proper message.
 *              Application handles the rest.
 * @param[IN]   None.
 * @retval      Any other error code apart from FSP_SUCCESS  unsuccessful to perform operation.
 **********************************************************************************************************************/
fsp_err_t read_Input_from_RTTViewer(void)
{
    fsp_err_t err = FSP_SUCCESS;     /* Error status */

    /* Variable to store user input */
    uint8_t rByte[BUFFER_SIZE] = { RESET_VALUE };
    uint8_t user_data          = RESET_VALUE;

    /* Read first byte of data provided by user */
    APP_READ(rByte);

    /* Conversion user data to integer value */
    user_data = (uint8_t)atoi((char *)&rByte);

    switch (user_data)
    {
        case ENABLE_WDT:
        {
            /* Enable WDT to count and generate NMI or Reset when the debugger (J-Link) is connected. */
            enable_wdt_count_in_debug_mode();

            /* If a bus-error flag is set, clear it to avoid repeated interrupts */
            if (1 == R_INTC->ERINTM33CTL0_b.ERRM30STAT0)
            {
                R_INTC->BECLR0 = 0xFFFFFFFF;
            }

            /* If the WDT‐overflow flag is set, clear it to avoid re‐entry */
            if (1 == R_INTC->ERINTM33CTL0_b.ERRM30STAT31)
            {
                R_INTC->ERINTM33CLR0_b.ERRM30CLR29 = 1U;
            }

            /* Open WDT. For every GTM timeout, WDT will get refreshed. */
            err = R_WDT_Open(&g_wdt_ctrl, &g_wdt_cfg);
            if ((FSP_SUCCESS != err) && (FSP_ERR_ALREADY_OPEN != err))
            {
                APP_ERR_PRINT("\r\n** R_WDT_Open API failed **\r\n");
                return err;
            }

            /* Register the user callback; the driver will call wdt_user_callback on an ICU error interrupt. */
            err = R_WDT_CallbackSet(&g_wdt_ctrl, wdt_user_callback, NULL, NULL);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n** R_WDT_CallbackSet API failed **\r\n");
                return err;
            }

            /* Arm the WDT hardware reset bit so that underflow triggers a system reset */
            R_BSP_WDT_SYSTEM_RESET_ENABLE(g_wdt_cfg_extend.channel, true);

            /* Enable the ICU Error_CM33 interrupt to catch WDT underflow events */
            R_BSP_IrqCfgEnable(ICU_ICUERR_CM33_IRQn, 24, &g_wdt_ctrl);

            /* Start GTM timer in Periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** timer_start for GTM failed **\r\n");
                return err;
            }

            /* Enable External IRQ */
            err = enable_irq_module();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** enable_irq_module failed **\r\n");
                return err;
            }

            /* Print message to indicate user about application status. */
            APP_PRINT("WDT initialized, GTM Timer Started\r\n");
            APP_PRINT("To stop WDT counter from refreshing, press the push button\r\n");
            break;
        }
        default:
        {
            /* Menu for user selection */
            APP_PRINT("Invalid Input\r\n");
            APP_PRINT("Please provide input from below option\r\n");
            APP_PRINT("Enter 1 to Enable WDT\r\n");
            APP_PRINT("User Input:  \r\n");
            break;
        }
    }

    return err;
}

/***********************************************************************************************************************
 * @brief       This function enables WDT counter to count in debug mode.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void enable_wdt_count_in_debug_mode(void)
{
    /* Clear this bit to Stop WDT0 from counting in debug mode */
    R_SYSC->SYS_WDT0_CTRL_b.WDTSTOPMASK = RESET_VALUE;
}

/***********************************************************************************************************************
 * @brief       This function is called to check whether reset is caused by WDT.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    /* Check if reset was caused by the WDT? If it was, turn on LED to indicate WDT reset triggered. */
    if (R_CPG->CPG_ERROR_RST2_b.ERROR_RST0)
    {
        /* Clear the flag or the test won't work properly the second time. */
        R_CPG->CPG_ERROR_RST2_b.ERROR_RST0_WEN = 1;
        R_CPG->CPG_ERROR_RST2_b.ERROR_RST0     = 1;
        g_timer_overflow_counter               = 0;

        /* Turn ON LED */
        /* Here is the place to add operations in accordance with User System.
         * In this sample, LED blink and debug message output operations are implemented. */

        /* If System Reset is enabled in the FSP configurator for the WDT stack,
         * this EP will not run because the DDR SDRAM resets as well.
         * Please adapt the behavior according to your system requirements. */
        R_BSP_PinWrite((bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_HIGH);

        APP_PRINT("\r\n************************ WDT Reset detected ************************\r\n");
    }
    else
    {
        /* Do nothing */
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at.
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* Allow access to IP beyond AXI */
        pd_all_on_postproc_axi();
        pd_all_on_postproc();
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_wdt_ep)
 **********************************************************************************************************************/
