/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "xspi_qspi_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_xspi_qspi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

uint8_t g_src[DATA_SIZE];

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Open the QSPI instance */
    err = R_XSPI_QSPI_Open(&g_qspi0_ctrl, &g_qspi0_cfg);
    if (FSP_SUCCESS != err)
    {   /* QSPI instance open failed */
        APP_PRINT("\r\n ** R_XSPI_QSPI OPEN FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Enter QPI mode */
    qspi_set_Quad_Mode_enable();
    APP_PRINT("[ENTER] QPI enabled\r\n");

    /*---------- Chip Erase ----------*/
    /*
    err = R_XSPI_QSPI_Erase(&g_qspi0_ctrl, (uint8_t *)QSPI_DEVICE_START_ADDRESS, SPI_FLASH_ERASE_SIZE_CHIP_ERASE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CHIP ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[CHIP ERASE] done.\r\n");
    }
    */

    /*---------- Sector Erase ----------*/
    uint8_t  * const p_erase_addr = (uint8_t *) QSPI_DEVICE_START_ADDRESS;
    uint32_t   const p_erase_len    = 4096U;
    APP_PRINT("[SECTOR ERASE] sector @0x%08X, Length %uB\r\n", p_erase_addr, (unsigned) p_erase_len);
    err = R_XSPI_QSPI_Erase(&g_qspi0_ctrl, p_erase_addr, p_erase_len);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[SECTOR ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[SECTOR ERASE] done.\r\n");
    }
   
    /* Wait for status register to update. */
    spi_flash_status_t status_erase;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_erase);
    } while (true == status_erase.write_in_progress);
    APP_PRINT("[ERASE] done\r\n");

    /*---------- Direct transfer (WRITE) ----------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06,  /* Write Enable */
    qspi_test_direct_transfer_write_enable.command_length = 1U,
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER WRITE] successfully\r\n");
    }
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write =
    {
        .command        = 0x02U,  /* 4PP instruction */
        .address        = 0x000234U,
        .data           = 0x12U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,
        .dummy_cycles   = 0U
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PAGE PROGRAM] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PAGE PROGRAM] ADDR=0x%08X LEN=%u data=0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_write.address,
                    (unsigned) qspi_test_direct_transfer_write.data_length,
                    (unsigned) (qspi_test_direct_transfer_write.data & 0xFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /*---------- Direct transfer (READ) ----------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_read =
    {
        .command        = 0xEBU,  /* 4READ instruction */
        .address        = 0x000234U,
        .data           = 0U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,
        .dummy_cycles   = 6U /* 4READ instruction needs 6 dummy cycles */
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_read, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER READ] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER READ] CMD=0x%02X addr=0x%08X dummy=%u LEN=%u -> 0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_read.command,
                    (unsigned) qspi_test_direct_transfer_read.address,
                    (unsigned) qspi_test_direct_transfer_read.dummy_cycles,
                    (unsigned) qspi_test_direct_transfer_read.data_length,
                    (unsigned) qspi_test_direct_transfer_read.data);
    }

    /*---------- Verify Write data = Read data? ----------*/
    if (qspi_test_direct_transfer_read.data != qspi_test_direct_transfer_write.data)
    {
        /* Exit QPI mode */
        APP_ERR_PRINT("[VERIFY] mismatch: wrote=0x%02X read=0x%02X\r\n",
                        qspi_test_direct_transfer_write.data, qspi_test_direct_transfer_read.data);
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    else
    {
        APP_PRINT("[VERIFY] direct transfer OK\r\n");
    }

    /*---------- Read data using memory-mapping mode ----------*/
    uint32_t read_buffer = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 +  qspi_test_direct_transfer_write.address); //xSPI0_CS0 memory (Mirror area)
    APP_PRINT("[MAP-READ] ADDR=0x%08X -> 0x%02X\r\n",
                (unsigned)qspi_test_direct_transfer_write.address, (unsigned) read_buffer);

    /*---------- Verify Write data = Read data? ----------*/
    if (read_buffer != qspi_test_direct_transfer_write.data)
    {
        /* Exit QPI mode */
        APP_ERR_PRINT("[VERIFY] mapped mismatch: w=0x%02X r=0x%02X\r\n",
                        (unsigned)(qspi_test_direct_transfer_write.data & 0xFFu),
                        (unsigned)read_buffer);
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    APP_PRINT("[VERIFY] mapped read OK\r\n");

    /*---------- Initialize Write Data ----------*/
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        g_src[i] = (uint8_t)i; /*conversion to 8-bit integer type */
    }
    APP_PRINT("[INITIALIZE] Prepared write data: %u bytes.\r\n", (unsigned)DATA_SIZE);

    /*---------- Write Data via write API ----------*/
    uint8_t * dest = (uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_ADDRESS);  /* xSPI0_CS0 memory, non-cache area use */
    err = R_XSPI_QSPI_Write(&g_qspi0_ctrl, g_src, dest, DATA_SIZE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE] OK\r\n");
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write2;
    do
    {
        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write2);
    } while (true == status_write2.write_in_progress);
    APP_PRINT("[WAIT] ready\r\n");

    /*---------- Verify Write data = Read data? ----------*/
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        uint8_t src_data = g_src[i];
        uint8_t dest_data = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_ADDRESS + i);
        if (src_data != dest_data)
        {
            APP_ERR_PRINT("[VERIFY] mismatch @+%u: w=0x%02X r=0x%02X\r\n",
                            (unsigned)i, (unsigned)src_data, (unsigned)dest_data);

            /* Exit QPI mode */
            qspi_set_Quad_Mode_disable();
            APP_ERR_TRAP(FSP_ERR_ASSERTION);
        }
    }

    APP_PRINT("[VERIFY] write API OK\r\n");

    /* Exit QPI mode */
    qspi_set_Quad_Mode_disable();
    APP_PRINT("[EXIT] QPI disabled\r\n");

    /* Close the application */
    APP_PRINT("[DONE]\r\n");
    while (1)
    {
        ;    /* Do nothing */
    }
}

/***********************************************************************************************************************
 * @brief     Enable Quad Peripheral Interface (QPI) and switch the controller to the 4S-4S-4S protocol.
 * @param[in] None
 * @return    None
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_enable(void)
{
    /* For following settings, temporary set protocol 1S-1S-1S */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*--------------- Read status register(RDSR) (05h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR = {0};
    direct_command_RDSR.command        = 0x05U;
    direct_command_RDSR.command_length = 1U;
    direct_command_RDSR.data_length    = 1U;

    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR.command,
                    (unsigned) direct_command_RDSR.data_length,
                    (unsigned) (direct_command_RDSR.data & 0xFFU));
    }

    uint32_t read_status = direct_command_RDSR.data;
    FSP_PARAMETER_NOT_USED(read_status);

    /*--------------------------------------------------------------*/

    /*---------------- Read configure register(RDCR) (15h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDCR = {0};
    direct_command_RDCR.command        = 0x15U;
    direct_command_RDCR.command_length = 1U;
    direct_command_RDCR.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDCR, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ CONFIGURE REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ CONFIGURE REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDCR.command,
                    (unsigned) direct_command_RDCR.data_length,
                    (unsigned) (direct_command_RDCR.data & 0xFFU));
    }
    uint32_t read_configure = direct_command_RDCR.data;
    FSP_PARAMETER_NOT_USED(read_configure);

    /*--------------------------------------------------------------*/

    /*--------------- Enable QPI mode(EQIO) (35h)---------------*/
    spi_flash_direct_transfer_t direct_command_EQIO = {0};
    direct_command_EQIO.command        = 0x35U;
    direct_command_EQIO.command_length = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_EQIO, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[ENABLE QPI MODE] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[ENABLE QPI MODE] sent: CMD=0x%02X\r\n", (unsigned)direct_command_EQIO.command);
    }

    /*--------------------------------------------------------------*/

    /* 4S-4S-4S protocol settings. */
    err = R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_4S_4S_4S);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PROTOCOL] Failed to set 4S-4S-4S: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PROTOCOL] 4S-4S-4S enabled\r\n");
    }

    /*--------------- Read status register(RDSR) (05h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR_2 = {0};
    direct_command_RDSR_2.command        = 0x05U;
    direct_command_RDSR_2.command_length = 1U;
    direct_command_RDSR_2.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR_2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer (after protocol) failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info (after protocol): CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR_2.command,
                    (unsigned) direct_command_RDSR_2.data_length,
                    (unsigned) (direct_command_RDSR_2.data & 0xFFU));
    }
    read_status = direct_command_RDSR_2.data;

    /*--------------------------------------------------------------*/

    /*---------------- Read configure register(RDCR) (15h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDCR_2 = {0};
    direct_command_RDCR_2.command        = 0x15U;
    direct_command_RDCR_2.command_length = 1U;
    direct_command_RDCR_2.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDCR_2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ CONFIGURE REGISTER] DirectTransfer (after protocol) failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ CONFIGURE REGISTER] info (after protocol): CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDCR_2.command,
                    (unsigned) direct_command_RDCR_2.data_length,
                    (unsigned) (direct_command_RDCR_2.data & 0xFFU));
        read_configure = direct_command_RDCR_2.data;
    }

    /*--------------------------------------------------------------*/
}

/***********************************************************************************************************************
 * @brief     Disable QPI mode and restore single-I/O SPI (1S-1S-1S) protocol.
 * @param[in] None
 * @return    None
 **********************************************************************************************************************/
void qspi_set_Quad_Mode_disable(void)
{
    /*--------------- Reset QPI(RSTQIO) (F5h)---------------*/
    spi_flash_direct_transfer_t direct_command_RSTQIO = {0};
    direct_command_RSTQIO.command        = 0xF5U;
    direct_command_RSTQIO.command_length = 1U;

    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RSTQIO, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[RESET QPI] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[RESET QPI] sent: CMD=0x%02X\r\n", (unsigned)direct_command_RSTQIO.command);
    }

    /*--------------------------------------------------------------*/

    /* 1S-1S-1S protocol settings. */
    err = R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PROTOCOL] Failed to set 1S-1S-1S: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PROTOCOL] 1S-1S-1S enabled\r\n");
    }

    /*--------------- Read status register (05h) ---------------*/
    spi_flash_direct_transfer_t direct_command = {0};
    direct_command.command        = 0x05U;
    direct_command.command_length = 1U;
    direct_command.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command.command,
                    (unsigned) direct_command.data_length,
                    (unsigned) (direct_command.data & 0xFFU));
    }

    /*--------------------------------------------------------------*/

    /*---------------- Read configure register (15h) ---------------*/
    direct_command.command        = 0x15U;
    direct_command.command_length = 1U;
    direct_command.data_length    = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ CONFIGURE REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ CONFIGURE REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command.command,
                    (unsigned) direct_command.data_length,
                    (unsigned) (direct_command.data & 0xFFU));
    }

    /*--------------------------------------------------------------*/
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_xspi_qspi_ep)
 **********************************************************************************************************************/
