/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "gpt_phase_count_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_gpt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    volatile fsp_err_t err = FSP_SUCCESS;

    static timer_status_t s_timer_status;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Array to store input from Tera Term */
    char input_Command[BUFFER_SIZE_DOWN];
    char input_data[DATA_LENGTH_BYTE * 2];

    /* Indicate whether the input string is a valid hexadecimal address */
    bool data_check_result = false;

    /* Hold the converted binary data from the validated hexadecimal input string */
    uint8_t conversionData[DATA_LENGTH_BYTE] = {0x00, 0x00, 0x00, 0x00};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* GPT driver initialization and start Phase Count */
    err = init_gpt_driver();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n** GPT driver initialization failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Menu printed on the console */
    APP_PRINT(MENU);

    while (true)
    {
        /* Check for input data from Tera Term, once data is available read */
        if (APP_CHECK_DATA)
        {
            memset(input_Command, NULL_CHAR, sizeof(input_Command));

            /* Read complete input instead of 1 byte to avoid processing of successive extra bytes entered */
            APP_READ((unsigned char *)input_Command);
            if (NULL_CHAR != input_Command[1])
            {
                APP_PRINT("\r\nInvalid input length. Please enter only one character.\n");
            }

            else
            {
                switch (input_Command[0])
                {
                    /* Get operation */
                    case 'g':
                    {
                        APP_PRINT("\r\nGet(g) executed.\r\n");
                        err = R_GPT_StatusGet(&g_timer_ctrl, &s_timer_status);

                        /* Handle error */
                        if (FSP_SUCCESS != err)
                        {
                            APP_ERR_PRINT("\r\n** R_GPT_StatusGet API failed **\r\n");
                            APP_ERR_TRAP(err);
                        }
                        APP_PRINT("%x\r\n", (unsigned int)s_timer_status.counter);
                        break;
                    }

                    /* Set operation */
                    case 's':
                    {
                        /* Input data */
                        APP_PRINT("\r\nEnter the Value:\r\n");
                        while (!APP_CHECK_DATA)
                        {
                            ; /* Wait for input_data value */
                        }
                        memset(input_data, RESET_VALUE, sizeof(input_data));
                        APP_READ((unsigned char *)input_data);

                        data_check_result = input_data_check(input_data, conversionData);
                        if (data_check_result)
                        {
                            APP_PRINT("\r\nSet(s) executed.\r\n");
                            s_timer_status.counter = (uint32_t)(
                            (conversionData[0] << 24) | (conversionData[1] << 16) |
                            (conversionData[2] << 8) | conversionData[3]);  /* Cast to uint32_t type */

                            err = R_GPT_Stop(&g_timer_ctrl);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n** R_GPT_Stop API failed **\r\n");
                                APP_ERR_TRAP(err);
                            }
                            err = R_GPT_CounterSet(&g_timer_ctrl, s_timer_status.counter);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n** R_GPT_CounterSet API failed **\r\n");
                                APP_ERR_TRAP(err);
                            }
                            err = R_GPT_Start(&g_timer_ctrl);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n** R_GPT_Start API failed **\r\n");
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("%x\r\n", (unsigned int)s_timer_status.counter);
                        }
                        break;
                    }

                    /* Reset operation */
                    case 'r':
                    {
                        err = R_GPT_Reset(&g_timer_ctrl);

                        /* Handle error */
                        if (FSP_SUCCESS != err)
                        {
                            APP_ERR_PRINT("\r\n** R_GPT_Reset API failed **\r\n");
                            APP_ERR_TRAP(err);
                        }
                        APP_PRINT("\r\nReset(r) executed.\r\n");
                        break;
                    }
                    default:
                    {
                        APP_PRINT("\r\nCommand Error!\r\n");
                        break;
                    }
                }
            }
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process. */

    /* Do not delete. Required to return to system_init. */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_gpt_ep)
 **********************************************************************************************************************/
