/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/
#include "common_utils.h"
#include "gtm_ep.h"
/***********************************************************************************************************************
 * @addtogroup r_gtm_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event);
FSP_CPP_FOOTER

volatile uint8_t g_one_shot_timer_flag = RESET_FLAG;    /* Flag to check timer is enable or not */
volatile uint8_t g_periodic_timer_flag = RESET_FLAG;    /* Flag to check timer1 is enable or not */
volatile uint32_t g_error_flag         = RESET_FLAG;    /* Flag to capture error in ISR's */
volatile uint32_t g_status_check_flag  = RESET_FLAG;    /* Flag to capture the status of timers */

/***********************************************************************************************************************
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Variables to store received data */
    unsigned char rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};

    /* Variables to store timer period values in milliseconds */
    uint32_t time_period_ms_oneshot  = RESET_VALUE;
    uint32_t time_period_ms_periodic = RESET_VALUE;

    /* Variables to store raw timer count values */
    uint32_t raw_counts_oneshot  = RESET_VALUE;
    uint32_t raw_counts_periodic = RESET_VALUE;

    /* Structures to store timer information */
    timer_info_t one_shot_info =
    {
        .clock_frequency = RESET_VALUE,
        .count_direction = (timer_direction_t) RESET_VALUE,
        .period_counts   = RESET_VALUE,
    };

    timer_info_t periodic_info =
    {
        .clock_frequency = RESET_VALUE,
        .count_direction = (timer_direction_t) RESET_VALUE,
        .period_counts   = RESET_VALUE,
    };

    /* Variable to store timer clock frequency */
    uint32_t clock_freq = RESET_VALUE;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize GTM driver */
    err = gtm_init();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* GTM module init failed */
        APP_ERR_PRINT(" ** gtm_init failed **\r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("Please enter time period values for one-shot and periodic mode timers in milliseconds\r\n"\
              "Valid range: 1 to 2000\r\n\r\n");
    APP_PRINT("One-shot mode:\r\n\r\n");

    while (true)
    {
        if (APP_CHECK_DATA)
        {
            /* Clean buffer */
            memset(&rByte[0], NULL_CHAR, BUFFER_SIZE_DOWN);
            APP_READ(rByte);
            time_period_ms_oneshot = (uint32_t)atoi((char *)rByte);

            if ((TIME_PERIOD_MAX >= time_period_ms_oneshot) && (TIME_PERIOD_MIN < time_period_ms_oneshot))
            {
                APP_PRINT("Time period for one-shot mode timer: %d\r\n\r\n", time_period_ms_oneshot);
                break;
            }
            else
            {
                APP_PRINT("Invalid input. Please enter valid input\r\n\r\n");
            }
        }
    }

    APP_PRINT("Periodic mode:\r\n\r\n");

    while (true)
    {
        if (APP_CHECK_DATA)
        {
            /* Clean buffer */
            memset(&rByte[0], NULL_CHAR, BUFFER_SIZE_DOWN);
            APP_READ(rByte);
            time_period_ms_periodic = (uint32_t)atoi((char *)rByte);

            if ((TIME_PERIOD_MAX >= time_period_ms_periodic) && (TIME_PERIOD_MIN < time_period_ms_periodic))
            {
                APP_PRINT("Time period for periodic mode timer: %d\r\n\r\n", time_period_ms_periodic);
                break;
            }
            else
            {
                APP_PRINT("Invalid input. Please enter valid input\r\n\r\n");
            }
        }
    }

    /* Calculation of raw counts value for given milliseconds value */
    err = R_GTM_InfoGet(&g_timer_one_shot_ctrl, &one_shot_info);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        gtm_deinit();
        APP_ERR_PRINT("** R_GTM_InfoGet API failed. Close all drivers. Restart the Application **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Depending on the user selected clock source, raw counts value can be calculated
     * for the user given time-period values */
    clock_freq = one_shot_info.clock_frequency;
    raw_counts_oneshot = (uint32_t)(time_period_ms_oneshot * (clock_freq / 1000));

    /* Set period value */
    err = R_GTM_PeriodSet(&g_timer_one_shot_ctrl, raw_counts_oneshot);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        gtm_deinit();
        APP_ERR_PRINT("** R_GTM_PeriodSet API failed. Close all drivers. Restart the Application **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Calculation of raw counts value for given milliseconds value */
    err = R_GTM_InfoGet(&g_timer_periodic_ctrl, &periodic_info);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        gtm_deinit();
        APP_ERR_PRINT("** R_GTM_InfoGet API failed. Close all drivers. Restart the Application *\r\n");
        APP_ERR_TRAP(err);
    }

    /* Depending on the user selected clock source, raw counts value can be calculated
     * for the user given time-period values */
    clock_freq = periodic_info.clock_frequency;
    raw_counts_periodic = (uint32_t)(time_period_ms_periodic * (clock_freq / 1000));

    /* Set period value */
    err = R_GTM_PeriodSet(&g_timer_periodic_ctrl, raw_counts_periodic);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        gtm_deinit();
        APP_ERR_PRINT("** R_GTM_PeriodSet API failed. Close all drivers. Restart the Application **\r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("Enter any key to start or stop the timers\r\n\r\n");

    while (true)
    {
        if (APP_CHECK_DATA)
        {
            /* Clean buffer */
            memset(&rByte[0], NULL_CHAR, BUFFER_SIZE_DOWN);
            APP_READ(rByte);
            g_status_check_flag = SET_FLAG;
        }

        if (SET_FLAG == g_status_check_flag)
        {
            /* Check the status of timers and perform operation accordingly */
            g_status_check_flag = RESET_FLAG;
            err = timer_status_check();

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                gtm_deinit();
                APP_ERR_PRINT("** timer_status_check failed **\r\n");
                APP_ERR_TRAP(err);
            }
        }

        /* Check if GTM0 is enabled in OneShot mode */
        if (SET_FLAG == g_one_shot_timer_flag)
        {
            g_one_shot_timer_flag = RESET_FLAG;
            APP_PRINT("GTM0 is Enabled in OneShot mode\r\n\r\n");
        }

        /* Check if GTM1 is enabled in Periodic mode */
        if (SET_FLAG == g_periodic_timer_flag)
        {
            g_periodic_timer_flag = RESET_FLAG;
            APP_PRINT("One-shot mode GTM timer elapsed\r\n");
            APP_PRINT("GTM1 is Enabled in Periodic mode\r\n");
            APP_PRINT("LED will toggle for set time period\r\n");
            APP_PRINT("Enter any key to stop timers\r\n\r\n");
        }

        /* Check if GTM1 is already running in Periodic mode */
        if (ALREADY_RUNNING == g_periodic_timer_flag)
        {
            g_periodic_timer_flag = RESET_FLAG;
            APP_PRINT("One-shot mode GTM timer elapsed\r\n\r\n");
            APP_PRINT("GTM1 is already running in Periodic mode\r\n");
            APP_PRINT("Enter any key to stop the timer\r\n\r\n");
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_gtm_ep)
 **********************************************************************************************************************/
