/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "i2c_pmic.h"
#include "common_utils.h"
#include "can_fd_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_can_fd_ep
 * @{
 **********************************************************************************************************************/

/* Structure with LED information for board. */
const bsp_leds_t g_leds =
{
    .led_count = (uint16_t)((sizeof(g_prv_leds)) / (sizeof(g_prv_leds[0]))),
    .p_leds    = &g_prv_leds[0]
};

/* User defined function */
static void led_pin_initialisation(void);

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rtt_input_buf[BUFFER_SIZE_DOWN] = {NULL_CHAR};

    /* Initialization of LED pins */
    led_pin_initialisation();

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize CANFD module */
    err = R_CANFD_Open(&g_canfd_ch4_ctrl, &g_canfd_ch4_cfg);

    /* Error trap */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\nR_CANFD_Open API failed");
        led_update(error);
        APP_ERR_TRAP(err);
    }

    err = R_CANFD_Open(&g_canfd_ch1_ctrl, &g_canfd_ch1_cfg);

    /* Error trap */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\nR_CANFD_Open API failed");
        led_update(error);
        APP_ERR_TRAP(err);
    }
    APP_PRINT("Please enter any key on Terminal Emulator to initiate CAN transmission.");

    while (1)
    {
        /* Check for user input */
        if (APP_CHECK_DATA)
        {
            APP_READ(rtt_input_buf);
            APP_PRINT("\nUser input: %s", (char *)rtt_input_buf);

            /* Update transmit frame and initiate transmission on CAN frame */
            canfd_operation();
        }

        /* Get the status of transmitted frame and read the data */
        can_read_operation();
        if (true == g_canfd_err_status)
        {
            g_canfd_err_status = false;
            APP_ERR_PRINT("\nCAN ERR status");
            led_update(error);
            APP_ERR_TRAP(true);
        }

        /* Re initializing time out value */
        g_time_out = WAIT_TIME;
    }
}

/***********************************************************************************************************************
 * @brief       This function initializes state of LED pins.
 * @param[in]   None.
 * @return      None.
 **********************************************************************************************************************/
static void led_pin_initialisation(void)
{
    /* Set the LED pin state low */
    R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[LED_LD0], BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[LED_LD1], BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[LED_LD2], BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[LED_LD3], BSP_IO_LEVEL_LOW);

    for (int i = 0; i < 4; i++)
    {
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[i], BSP_IO_LEVEL_HIGH);

        /* Delay */
        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
    }

    for (int j = 3; j >= 0; j--)
    {
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_leds.p_leds[j], BSP_IO_LEVEL_LOW);

        /* Delay */
        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at.
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_can_fd_ep)
 **********************************************************************************************************************/
