/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "doc_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_doc_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/* Expected DOC accumulated results after each overflow interrupt */
uint32_t g_expected_value[] = {0xF000, 0xE000, 0xD000, 0xC000, 0xB000};

extern uint32_t g_callback_event_counter;

/* Clear DOC operation complete flag (DOPCF) before starting a new operation */
static void doc_clear_flag(void)
{
    R_DOC->DOCR |= R_DOC_DOCR_DOPCFCL_Msk;
}

/* Poll until DOC operation complete flag (DOPCF) is set */
static void doc_wait_flag_polling(void)
{
    while ((R_DOC->DOCR & R_DOC_DOCR_DOPCF_Msk) == 0U)
    {
        ;
    }
}

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);

    /* Print the EP information on the RTT Viewer */
    APP_PRINT(EP_INFO);

    /* Set PERIERR register and enable PERI_ERR0 interrupt to configure behavior when the DOC event occurs */
    error_int_setting();

    /* Initialize the DOC module */
    err = R_DOC_Open(&g_doc_ctrl, &g_doc_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_DOC_Open API failed\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable DOPCI error interrupt */
    R_DOC->DOCR |= (uint8_t) (R_DOC_DOCR_DOPCFCL_Msk | R_DOC_DOCR_DOPCIE_Msk);

    g_callback_event_counter = 0;
    doc_clear_flag();

    switch (g_doc_cfg.event)
    {
        case DOC_EVENT_COMPARISON_MATCH:
        {
            APP_PRINT("\r\nEvent: Comparison Match");

            /* Reference data */
            R_DOC->DODSR = DOC_REF_DATA_MATCH;

            /* Write matching data */
            err = R_DOC_Write(&g_doc_ctrl, DOC_REF_DATA_MATCH);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("R_DOC_Write API failed\r\n");
                APP_ERR_TRAP(err);
            }

            /* Poll for DOC event */
            doc_wait_flag_polling();

            APP_PRINT("\r\nDOC Comparison Match successful");
            break;
        }
        case DOC_EVENT_COMPARISON_MISMATCH:
        {
            APP_PRINT("\r\nEvent: Comparison Mismatch");

            /* Reference data */
            R_DOC->DODSR = DOC_REF_DATA_MISMATCH;

            /* Write mismatching data */
            err = R_DOC_Write(&g_doc_ctrl, DOC_CMP_INPUT_MISMATCH);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("R_DOC_Write API failed\r\n");
                APP_ERR_TRAP(err);
            }

            /* Poll for DOC event */
            doc_wait_flag_polling();

            APP_PRINT("\r\nDOC Comparison Mismatch successful");
            break;
        }
        case DOC_EVENT_ADDITION:
        {
            APP_PRINT("\r\nEvent: Addition Overflow");

            /* Initialize value */
            R_DOC->DODSR = DOC_ADD_INITIAL_VALUE;

            for (uint32_t i = 0; i < 2; i++)
            {
                err = R_DOC_Write(&g_doc_ctrl, DOC_ADD_INPUT_VALUE);
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT("R_DOC_Write API failed\r\n");
                    APP_ERR_TRAP(err);
                }
                R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);
            }

            /* Wait for PERI_ERR0 ISR */
            while (RESET_VALUE == g_callback_event_counter)
            {
                ;
            }
            APP_PRINT("\r\nDOC Addition Overflow successful");
            break;
        }
        case DOC_EVENT_SUBTRACTION:
        {
            APP_PRINT("\r\nEvent: Subtraction Underflow");

            /* Initialize value */
            R_DOC->DODSR = DOC_SUB_INITIAL_VALUE;

            err = R_DOC_Write(&g_doc_ctrl, DOC_SUB_INPUT_VALUE);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("R_DOC_Write API failed\r\n");
                APP_ERR_TRAP(err);
            }
            R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);

            /* Wait for PERI_ERR0 ISR */
            while (RESET_VALUE == g_callback_event_counter)
            {
                ;
            }
            APP_PRINT("\r\nDOC Subtraction Underflow successful");
            break;
        }
        default:
        {
            APP_ERR_PRINT("\r\nUnsupported DOC event");
            APP_ERR_TRAP(FSP_ERR_INVALID_ARGUMENT);
            break;
        }
    }
    APP_PRINT("\r\nDOC EP finished");
    while (1)
    {
        /* Do nothing */
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process. */

    /* Do not delete. Required to return to system_init. */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_doc_ep)
 **********************************************************************************************************************/
