/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "dmac_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_dmac_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/*
 * Private Global Variables
 */
void user_dmac_callback (transfer_callback_args_t * p_args);

volatile bool g_transfer_complete = false;

uint8_t g_p_src0[TRANSFER_LENGTH_0];
uint8_t g_p_dest0[TRANSFER_LENGTH_0];

uint8_t g_p_src1[TRANSFER_LENGTH_1];
uint8_t g_p_dest1[TRANSFER_LENGTH_1];


/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Variable to help handle error codes from functions*/
    fsp_err_t err = FSP_SUCCESS;

    /* fsp variable to store major/minor versions*/
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize g_p_src0 */
    for (uint32_t i = 0; i < TRANSFER_LENGTH_0; i++)
    {
        g_p_src0[i] = (uint8_t) ('A' + (i % 26));
    }

    /* Initialize g_p_src1 */
    for (uint32_t i = 0; i < TRANSFER_LENGTH_1; i++)
    {
        g_p_src1[i] = (uint8_t) ('0' + (i % 10));
    }

    /* Initialize DMAC driver */
    err = init_dmac_driver();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DMAC driver initialization failed  */
        APP_ERR_PRINT("\r\n ** DMAC driver initialization FAILED ** \r\n");

        APP_ERR_TRAP(err);
    }

    /* Initialize CMTW timer driver */
    err = init_CMTW_timer_driver();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DMAC driver initialization failed  */
        APP_ERR_PRINT("\r\n ** CMTW timer initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\r\n*** Reconfiguring DMAC to transfer from src0 to dest0 *** \r\n");

    /* Set Transfer settings by using reconfigure API. */
    reconfigure_transfer_settings(g_p_src0, g_p_dest0, TRANSFER_MODE_BLOCK);

    /* SoftwareStart */
    /* Note: When executing SoftwareStart API continuously without calling Reconfigure API, */
    /*       Enable API must be called in advance.                                          */
    /*       (EN bit is automatically cleared after the transfer.                           */
    /*        see RZ microprocessor 'CHSTAT_n : Channel Status Register n' section)         */
    err = R_DMAC_SoftwareStart(&g_transfer_ctrl, (transfer_start_mode_t)NULL);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DMAC SoftwareStart failed  */
        APP_ERR_PRINT("\r\n ** DMAC SoftwareStart FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    while (!g_transfer_complete)
    {
        ;   /* Wait for transfer complete interrupt */
    }

    g_transfer_complete = false;

    APP_PRINT("\r\n*** Data successfully transferred *** \n");
    APP_PRINT("*** Destination array after transfer dest0: *** \n");
    dmac_transfer_print_data(g_p_dest0, 26);

    APP_PRINT("\r\n*** Reconfiguring DMAC to transfer from src1 to dest1 *** \r\n");

    /* Set Transfer settings by using reconfigure API. */
    reconfigure_transfer_settings(g_p_src1, g_p_dest1, TRANSFER_MODE_NORMAL);

    /* Start the timer for DMAC trigger. */
    (void)R_CMTW_Start(&g_timer_ctrl);

    while (!g_transfer_complete)
    {
        ;   /* Wait for transfer complete interrupt */
    }

    APP_PRINT("\r\n*** Data successfully transferred *** \n");
    APP_PRINT("*** Destination array after transfer dest1: *** \n");
    dmac_transfer_print_data(g_p_dest1, 20);

    while (1)
    {
        ;   /* Do nothing */
    }
}

/***********************************************************************************************************************
 *  @brief        User defined DMAC callback function.
 *  @param[in]    p_args
 *  @retval       None
 **********************************************************************************************************************/
void user_dmac_callback (transfer_callback_args_t * p_args)
{
    if (TRANSFER_EVENT_TRANSFER_END == p_args->event)
    {
        g_transfer_complete = true;
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_dmac_ep)
 **********************************************************************************************************************/
