/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"

extern bsp_leds_t g_bsp_leds;

#define TIMEOUT     (10000000U)
#define LOOP_COUNT  (10U)

/***********************************************************************************************************************
 * @addtogroup r_cgc_ep
 * @{
 **********************************************************************************************************************/
/* Private functions */

static void led_blink (uint32_t loop_count);

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version =   { RESET_VALUE };
    cgc_divider_cfg_t cgc_divider_cfg;
    cgc_clocks_cfg_t  clocks_cfg;

    /* Get the FSP version */
    R_FSP_VersionGet (&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);

    /* Initialize CGC driver */
    err = R_CGC_Open (&g_cgc_ctrl, &g_cgc_cfg);

    if (FSP_SUCCESS != err)
    {   /* CGC module init failed */
        APP_PRINT("\r\n ** CGC INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\nCGC switches CPU operating Clock to slowest settings.\n");

    /* Clock configuration (Switching to slowest clock settings.) */
    cgc_divider_cfg.sckcr_b.fselxspi0       = CGC_FSEL_XSPI_CLOCK_DIV_64;
    cgc_divider_cfg.sckcr_b.fselxspi1       = CGC_FSEL_XSPI_CLOCK_DIV_64;
    cgc_divider_cfg.sckcr_b.ckio_div        = CGC_CLOCK_OUT_CLOCK_DIV_8;
    cgc_divider_cfg.sckcr_b.fselcanfd_div   = CGC_CANFD_CLOCK_DIV_20;
    cgc_divider_cfg.sckcr_b.phy_sel         = CGC_PHY_CLOCK_PLL1;
    cgc_divider_cfg.sckcr_b.spi0_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.spi1_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.spi2_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci0_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci1_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci2_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci3_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci4_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;

    cgc_divider_cfg.sckcr2_b.fsel0cr52      = CGC_CPU_CLOCK_DIV_4;
    cgc_divider_cfg.sckcr2_b.div_sub_sel    = CGC_BASECLOCK_DIV_4;
    cgc_divider_cfg.sckcr2_b.spi3_async_sel = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr2_b.sci5_async_sel = CGC_SCI_ASYNC_CLOCK_96MHZ;

    clocks_cfg.pll1_state                   = CGC_CLOCK_CHANGE_START;
    clocks_cfg.loco_state                   = CGC_CLOCK_CHANGE_START;
    clocks_cfg.divider_cfg                  = cgc_divider_cfg;

    /* Configure CGC Clock */
    err = R_CGC_ClocksCfg (&g_cgc_ctrl, &clocks_cfg);

    if (FSP_SUCCESS != err)
    {   /* CGC configure clock failed */
        APP_PRINT("\r\n ** CGC CONFIGURE CLOCK FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\nThe LED blinks at slowest clock.\n");

    /* LED Blink function */
    led_blink(LOOP_COUNT);

    APP_PRINT("\nCGC switches CPU operating Clock to fastest settings.\n");

    /* Clock configuration (Switching to fastest clock settings.) */
    cgc_divider_cfg.sckcr_b.fselxspi0       = CGC_FSEL_XSPI_CLOCK_DIV_6;
    cgc_divider_cfg.sckcr_b.fselxspi1       = CGC_FSEL_XSPI_CLOCK_DIV_6;
    cgc_divider_cfg.sckcr_b.ckio_div        = CGC_CLOCK_OUT_CLOCK_DIV_3;
    cgc_divider_cfg.sckcr_b.fselcanfd_div   = CGC_CANFD_CLOCK_DIV_10;
    cgc_divider_cfg.sckcr_b.phy_sel         = CGC_PHY_CLOCK_MAIN_OSC;
    cgc_divider_cfg.sckcr_b.spi0_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.spi1_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.spi2_async_sel  = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci0_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci1_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci2_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci3_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr_b.sci4_async_sel  = CGC_SCI_ASYNC_CLOCK_96MHZ;

    cgc_divider_cfg.sckcr2_b.fsel0cr52      = CGC_CPU_CLOCK_DIV_1;
    cgc_divider_cfg.sckcr2_b.div_sub_sel    = CGC_BASECLOCK_DIV_3;
    cgc_divider_cfg.sckcr2_b.spi3_async_sel = CGC_SPI_ASYNC_CLOCK_96MHZ;
    cgc_divider_cfg.sckcr2_b.sci5_async_sel = CGC_SCI_ASYNC_CLOCK_96MHZ;

    clocks_cfg.pll1_state                   = CGC_CLOCK_CHANGE_STOP;
    clocks_cfg.loco_state                   = CGC_CLOCK_CHANGE_START;
    clocks_cfg.divider_cfg                  = cgc_divider_cfg;

    /* Configure CGC Clock */
    err = R_CGC_ClocksCfg (&g_cgc_ctrl, &clocks_cfg);

    if (FSP_SUCCESS != err)
    {   /* CGC configure clock failed */
        APP_PRINT("\r\n ** CGC CONFIGURE CLOCK FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\nThe LED blinks at fastest clock.\n");

    /* LED Blink function */
    led_blink(LOOP_COUNT);

    APP_PRINT("\r\n ** Exiting CGC Demo ** \r\n");
    while (true)
    {
        ;
    }
}

/***********************************************************************************************************************
 * @brief       This function toggles on board LED.
 * @param[IN]   loop_count                  Number of round to blink LED
 * @retval      None
 **********************************************************************************************************************/
static void led_blink(uint32_t loop_count) {
    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* If this board has no LEDs then trap here */
    if (0 == leds.led_count)
    {
        while (1)
        {
            ;                          /* There are no LEDs on this board */
        }
    }

    /* This code uses BSP IO functions to show how it is used.*/
    /* Turn off LEDs */
    for (uint32_t i = 0; i < leds.led_count; i++)
    {
        R_BSP_PinClear((bsp_io_region_t)leds.p_leds[i][1], (bsp_io_port_pin_t)leds.p_leds[i][0]);
    }

    for (uint32_t loop = 0; loop < loop_count; loop++)
    {
        /* Toggle board LEDs */
        for (uint32_t i = 0; i < leds.led_count; i++)
        {
            R_BSP_PinToggle((bsp_io_region_t)leds.p_leds[i][1], (bsp_io_port_pin_t)leds.p_leds[i][0]);
        }

        /* Software Delay */
        for (volatile uint32_t j = 0; j < TIMEOUT; j++); /* Do nothing. */
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_cgc_ep)
 **********************************************************************************************************************/
