/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "crc_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_crc_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/* Sample input data buffer for 8-bit CRC calculation */
uint8_t g_data_8bit[] =
{
    1, 2, 3, 4, 5, 6, 7, 8, 9
};

/* Buffer to store the calculated CRC result */
uint32_t g_crc_buff;

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t  version =  {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;
    uint32_t length;
    uint32_t crc_calculated_value;
    length = sizeof(g_data_8bit) / sizeof(g_data_8bit[0]);

    crc_input_t example_input =
    {
        .p_input_buffer = g_data_8bit,
        .num_bytes      = length,
        .crc_seed       = 0,
    };

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);

    /* Print the EP information on the TeraTerm */
    APP_PRINT(EP_INFO);

    /* Open CRC module with 8 bit polynomial */
    err = R_CRC_Open(&g_crc0_ctrl, &g_crc0_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\nR_CRC_Open API failed.");
        APP_ERR_TRAP(err);
    }

    /* 8-bit CRC calculation */
    err = R_CRC_Calculate(&g_crc0_ctrl, &example_input, &crc_calculated_value);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\nR_CRC_Calculate API failed.\r\n");
        APP_ERR_TRAP(err);
    }

    if (EXPECTED_CRC_VALUE != crc_calculated_value)
    {
        /* CRC mismatch: calculated value does not match expected value */
        APP_ERR_PRINT("\r\nCRC mismatch: calculated value does not match expected value.\r\n");
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* CRC calculation successful: calculated value matches expected value */
    APP_PRINT("\r\nCRC calculation successful: calculated value matches expected value.\r\n");

    while (1)
    {
        /* Do nothing */
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process. */

    /* Do not delete. Required to return to system_init. */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_crc_ep)
 **********************************************************************************************************************/
