/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "can_fd_ep.h"

/***********************************************************************************************************************
 * @addtogroup can_fd_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION (".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    uint8_t             rtt_input_buf[BUFFER_SIZE_DOWN]  =  {NULL_CHAR};

    fsp_pack_version_t  version                          =  {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    
    /* Print the EP information on the RTT viewer */
    APP_PRINT (EP_INFO);

    canfd_entry();

    APP_PRINT("\nPlease enter any key on Terminal Emulator to initiate CAN transmission.\n");

    while (1)
    {
        /* Check for user input */
        if (APP_CHECK_DATA)
        {
            APP_READ(rtt_input_buf);
            APP_PRINT("\nUser input: %s" , rtt_input_buf);

            /* Update transmit frame and initiate transmission on CAN frame */
            canfd_operation();
        }

        /* Get the status of transmitted frame and read the data */
        can_read_operation();
        if (true == g_b_canfd_err_status)
        {
            g_b_canfd_err_status = false;
            APP_ERR_PRINT("\nCAN ERR status");
            APP_ERR_TRAP(true);
        }

        /* Re initializing time out value */
        g_time_out = WAIT_TIME;
    }
}
/***********************************************************************************************************************
 * End of function: hal_entry
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */;
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
/***********************************************************************************************************************
 * End of function: R_BSP_WarmStart
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @} (end addtogroup can_fd_ep)
 **********************************************************************************************************************/
