/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "xspi_init.h"
#include "ca55_start.h"
#include "cm33_fpu_start.h"
#include "common_utils.h"
#include "intc_irq_ep.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/***********************************************************************************************************************
 * @addtogroup r_intc_irq_ep
 * @{
 **********************************************************************************************************************/

/* Board's user LED */
extern bsp_leds_t g_bsp_leds;

/* Boolean flag to determine switch is pressed or not */
extern volatile bool g_sw_press;

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry (void)
{
    fsp_err_t err                           = FSP_SUCCESS;
    bsp_io_level_t led_current_state        = (bsp_io_level_t) RESET_VALUE;
    fsp_pack_version_t version              = {RESET_VALUE};

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the RTT */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
               version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize external IRQ driver */
    err = intc_irq_init();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** intc_irq_init failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable external IRQ driver */
    err = intc_irq_enable();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** intc_irq_enable failed **\r\n");

        /* Close external IRQ module */
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == leds.led_count)
    {
        APP_PRINT("\r\nThere are no LEDs on this board\r\n");

        /* Close external IRQ module */
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* Main loop */
    while (true)
    {
        /* Toggle user LED when user push button is pressed */
        if (true == g_sw_press)
        {
            /* Clear user push button flag */
            g_sw_press = false;

            /* Notify that user push button is pressed */
            APP_PRINT("\r\nUser push button pressed\r\n");

            /* Read user LED pin */
            for (uint32_t i = 0; i < g_bsp_leds.led_count; i++)
            {
                /* Get pin to toggle */
                bsp_io_port_pin_t pin = g_bsp_leds.p_leds[i];

                /* Read from this pin */
                err = R_IOPORT_PinRead(&g_ioport_ctrl, pin, &led_current_state);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT("** R_IOPORT_PinRead API failed **\r\n");

                    /* Close External IRQ module */
                    intc_irq_deinit();
                    APP_ERR_TRAP(err);
                }
            }

            /* Reverse LED pin state */
            led_current_state ^= BSP_IO_LEVEL_HIGH;

            /* Toggle user LED */
            for (uint32_t i = 0; i < g_bsp_leds.led_count; i++)
            {
                /* Get pin to toggle */
                uint32_t pin = g_bsp_leds.p_leds[i];

                /* Write to this pin */
                err = R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)pin, led_current_state);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT("** R_IOPORT_PinWrite API failed **\r\n");

                    /* Close External IRQ module */
                    intc_irq_deinit();
                    APP_ERR_TRAP(err);
                }
            }
            if (BSP_IO_LEVEL_HIGH == led_current_state)
            {
                /* Print LED Pin state */
                APP_PRINT("LED State: High{ON}\r\n");
            }
            else
            {
                /* Print LED Pin state */
                APP_PRINT("LED State: Low{OFF}\r\n");
            }
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[IN]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        if (0 == (R_SYSC_SYS_LSI_MODE_STAT_BOOTCPUSEL_Msk & R_SYSC->SYS_LSI_MODE))
        {
            xspi_open();

#if BSP_CFG_MCU_LAUNCH_CM33_FPU

            /* Load Cortex-M33_FPU program to SRAM(MCPU) */
            load_cm33fpu_prog();

            /* Release reset of Cortex-M33_FPU */
            release_reset_cm33_fpu();
#endif

#if BSP_CFG_MCU_LAUNCH_CA55

            /* Load Cortex-A55 program to SRAM(ACPU) */
            load_ca55_prog();

            xspi_close();

            /* Release reset of Cortex-A55(Core0) */
            release_reset_ca55();
#endif
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_intc_irq_ep)
 **********************************************************************************************************************/
