/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2025 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "spi_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_rspi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    uint8_t            converted_serial_input  = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize SPI driver */
    err = spi_init();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* SPI module initialization failed */
        APP_ERR_PRINT("** spi_init failed **\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("** SPI initialization successful **\r\n");
    }

    /* Menu for the user selection */
    APP_PRINT("\r\nSelect from the below menu options\r\n");
    APP_PRINT("Press 1 for Write() and Read()\r\n");
    APP_PRINT("Press 2 for WriteRead()\r\n");
    APP_PRINT("Press 3 to exit\r\n");

    while (EXIT != converted_serial_input)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            APP_PRINT("\r\n");
            converted_serial_input = (uint8_t)atoi((char *)rByte);

            switch (converted_serial_input)
            {
                case WRITE_AND_READ:
                    err = spi_write_and_read();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE AND READ demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE AND READ demo successful **\r\n");
                    }
                    break;
                case WRITE_READ:
                    err = spi_write_read();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE READ demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE READ demo successful **\r\n");
                    }
                    break;
                case EXIT:
                    err = spi_exit_demo();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI EXIT demo failed **\r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI EXIT demo successful **\r\n");
                    }
                    break;
                default:

                    /* Menu for the user selection */
                    APP_PRINT("\r\nSelect from the below menu options\r\n");
                    APP_PRINT("Press 1 for Write() and Read()\r\n");
                    APP_PRINT("Press 2 for WriteRead()\r\n");
                    APP_PRINT("Press 3 to exit\r\n");
                    break;
            }
            if ((WRITE_AND_READ <= converted_serial_input) && (EXIT > converted_serial_input))
            {
                APP_PRINT("Enter any other key to go back to the main menu\r\n");
        }
    }

    }

    APP_PRINT("Exiting SPI demo....\r\n");
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU */
        R_MMU_Open(&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_rspi_ep)
 **********************************************************************************************************************/
