/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "xspi_init.h"
#include "ca55_start.h"
#include "cm33_fpu_start.h"
#include "common_utils.h"
#include "timer_setup.h"
#include "ext_irq_setup.h"

/***********************************************************************************************************************
 * @addtogroup r_wdt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/*
 * External Global Variables
 */
/* LED structure used to blink on board LED */
extern          bsp_leds_t g_bsp_leds;
extern volatile uint8_t    g_timer_overflow_counter;

/*
 * Private function declarations
 */

/* Function used to read J-Link RTT Viewer input and proceed */
static fsp_err_t read_Input_from_RTTViewer (void);

/* Function used to enable WDT in debug mode */
static void enable_wdt_count_in_debug_mode (void);

/* Function used to check if reset is caused by WDT or not */
static void check_reset_status (void);

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
               version.version_id_b.patch);
    APP_PRINT(EP_INFO);
    
    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == g_bsp_leds.led_count)
    {
        APP_PRINT("** No on-board LEDs Found **\r\n");
        APP_ERR_TRAP(FSP_ERR_UNSUPPORTED);
    }

    check_reset_status();

    /* Initialize GTM in periodic mode */
    err = init_gtm_module();
    if (FSP_SUCCESS != err)
    {
        /* Timer init failed */
        APP_ERR_PRINT("** init_gtm_module failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initialize external IRQ */
    err = init_irq_module();
    if (FSP_SUCCESS != err)
    {
        /* External IRQ init failed, cleanup the timer initialization */
        APP_ERR_PRINT("** init_irq_module failed **\r\n");
        deinit_gtm_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for user selection */
    APP_PRINT("\r\nEnter 1 to Enable WDT\r\n");
    APP_PRINT("\r\nUser Input:\r\n");

    while (true)
    {
        /* Process input only when user has provided one */
        if (APP_CHECK_DATA)
        {
            err = read_Input_from_RTTViewer();
            if (FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ module */
                deinit_gtm_module();
                deinit_irq_module();
                APP_ERR_TRAP(err);
            }
        }

        /* For every 3Sec. J-Link RTT Viewer prints WDT refresh message.
         * This is done to avoid the continuous print message on J-Link RTT Viewer */
        if (WDT_REFRESH_COUNTER_VALUE == g_timer_overflow_counter)
        {
            g_timer_overflow_counter = RESET_VALUE;
            APP_PRINT("WDT counter Refreshed.\r\n");
        }
    }
}

/***********************************************************************************************************************
 * @brief       Read user input from J-Link RTT Viewer. Handle the Error internally with Proper Message. 
 *              Application handles the rest.
 * @param[IN]   None.
 * @retval      Any Other Error code apart from FSP_SUCCESS  Unsuccessful to perform operation.
 **********************************************************************************************************************/
fsp_err_t read_Input_from_RTTViewer(void)
{
    fsp_err_t err = FSP_SUCCESS;     /* Error status */

    /* Variable to store user input */
    uint8_t rByte[BUFFER_SIZE] = { RESET_VALUE };
    uint8_t user_data          = RESET_VALUE;

    /* Read first byte of data provided by user */
    APP_READ(rByte);

    /* Cast atoi() return value to char for assignment */
    user_data = (uint8_t)atoi((char *)&rByte); 

    switch (user_data)
    {
        case ENABLE_WDT:
        {
            /* Enable WDT to count and generate NMI or reset when the debugger(JLink) is connected */
            enable_wdt_count_in_debug_mode();

            /* Open WDT for every GTM timeout, WDT will get refreshed */
            err = R_WDT_Open(&g_wdt_ctrl, &g_wdt_cfg);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_WDT_Open API failed **\r\n");
                return err;
            }

            /* Start GTM timer in periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** timer_start failed **\r\n");
                return err;
            }

            /* Enable external IRQ */
            err = enable_irq_module();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** enable_irq_module failed **\r\n");
                return err;
            }

            /* Print message to indicate user about application status */
            APP_PRINT("WDT initialized, GTM timer started\r\n");
            APP_PRINT("To stop WDT counter from refreshing, press the push button\r\n");
            break;
        }
        default:
        {
            /* Menu for user selection */
            APP_PRINT("Invalid input\r\n");
            APP_PRINT("Please provide input from below option\r\n");
            APP_PRINT("Enter 1 to enable WDT\r\n");
            APP_PRINT("User input: \r\n");
            break;
        }
    }
    user_data = RESET_VALUE;
    return err;
}

/***********************************************************************************************************************
 * @brief       This function is called to enable WDT counter in debug mode.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void enable_wdt_count_in_debug_mode(void)
{
    /* Clear this bit to stop WDT1 from counting in debug mode */
    R_SYSC->SYS_WDT1_CTRL_b.WDTSTOPMASK = RESET_VALUE;
}

/***********************************************************************************************************************
 * @brief       This function is called to check whether reset is caused by WDT.
 * @param[IN]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    /* Check if reset was caused by the WDT? If it was, turn on LED to indicate WDT reset triggered */
    if (R_CPG_CPG_WDTOVF_RST_WDTOVF1 == R_CPG->CPG_WDTOVF_RST_b.WDTOVF1)
    {
        /* Clear the flag once read the value */
        R_CPG->CPG_WDTOVF_RST = R_CPG_CPG_WDTOVF_RST_WDTOVF1_Msk | R_CPG_CPG_WDTOVF_RST_WDTOVF1_WEN_Msk;

        /* Turn ON LED */
        /* Here is the place to add operations in accordance with user system.
         * In this sample, LED blink and debug message output operations are implemented */

        /* If system reset is enabled in the FSP configurator for the WDT stack,
         * this EP will not run because the DDR SDRAM resets as well.
         * Please adapt the behavior according to your system requirements */
        R_BSP_PinWrite((bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_HIGH);

        APP_PRINT("\r\n************************ WDT Reset detected ************************\r\n");
    }
    else
    {
        ;/* Do nothing */
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[IN]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

        /* Configure pins */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        if (0 == (R_SYSC_SYS_LSI_MODE_STAT_BOOTCPUSEL_Msk & R_SYSC->SYS_LSI_MODE))
        {
            xspi_open();

#if BSP_CFG_MCU_LAUNCH_CM33_FPU

            /* Load Cortex-M33_FPU program to SRAM(MCPU) */
            load_cm33fpu_prog();

            /* Release reset of Cortex-M33_FPU */
            release_reset_cm33_fpu();
#endif

#if BSP_CFG_MCU_LAUNCH_CA55

            /* Load Cortex-A55 program to SRAM(ACPU) */
            load_ca55_prog();

            xspi_close();

            /* Release reset of Cortex-A55(Core0) */
            release_reset_ca55();
#endif
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_wdt_ep)
 **********************************************************************************************************************/
