/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "cmt_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_cmt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

extern bsp_leds_t g_bsp_leds;

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t          err     = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize the CMT module. */
    err = R_CMT_Open(&g_timer0_ctrl, &g_timer0_cfg);
    if (FSP_SUCCESS != err)
    {   /* CMT module init failed */
        APP_PRINT("\r\n ** CMT INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Start the timer. */
    err = R_CMT_Start(&g_timer0_ctrl);
    if (FSP_SUCCESS != err)
    {
        APP_PRINT("\r\n ** CMT START FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    while (1)
    {
        /* Do nothing */
    }
}

/***********************************************************************************************************************
 * @brief     Timer ISR: p_args->event == TIMER_EVENT_CYCLE_END, toggle all BSP LEDs and print a log line.
 * @param[in] p_args  Pointer to timer_callback_args_t from the timer driver.
 * @return    None
 **********************************************************************************************************************/
void timer_callback (timer_callback_args_t * p_args)
{
    if (TIMER_EVENT_CYCLE_END == p_args->event)
    {
        /* LED type structure */
        bsp_leds_t leds = g_bsp_leds;

        /* If this board has no LEDs then trap here */
        if (0 == leds.led_count)
        {
            while (1)
            {
                ;                          /* There are no LEDs on this board */
            }
        }

        /* This code uses BSP IO functions to show how it is used.*/
        R_BSP_PinAccessEnable();

        /* Update all board LEDs */
        for (uint32_t i = 0; i < leds.led_count; i++)
        {
            /* Write to this pin */
            R_BSP_PinToggle((bsp_io_region_t)leds.p_leds[i][1], (bsp_io_port_pin_t)leds.p_leds[i][0]);
        }

        /* Protect PFS registers */
        R_BSP_PinAccessDisable();
        APP_PRINT("Interrupt occurred: LED toggled\r\n");
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_cmt_ep)
 **********************************************************************************************************************/
