/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "intc_irq_ep.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * @addtogroup r_intc_irq_ep
 * @{
 **********************************************************************************************************************/

/* Board's user LED. */
extern bsp_leds_t g_bsp_leds;

/* Boolean flag to determine switch is pressed or not. */
extern volatile bool g_sw_press;

/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err                           = FSP_SUCCESS;
    bsp_io_level_t led_current_state        = (bsp_io_level_t) RESET_VALUE;
    fsp_pack_version_t version              = {RESET_VALUE};

    /* LED type structure. */
    bsp_leds_t leds = g_bsp_leds;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the RTT */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major,
              version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize external IRQ driver */
    err = intc_irq_init();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** intc_irq_init failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable external IRQ driver */
    err = intc_irq_enable();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** intc_irq_enable failed **\r\n");

        /* Close external IRQ module. */
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* If this board has no LEDs then trap here. */
    if (RESET_VALUE == leds.led_count)
    {
        APP_PRINT("\r\nThere are no LEDs on this board\r\n");

        /* Close external IRQ module. */
        intc_irq_deinit();
        APP_ERR_TRAP(err);
    }

    /* Main loop. */
    while (true)
    {
        /* Toggle user LED when user pushbutton is pressed. */
        if (true == g_sw_press)
        {
            /* Clear user pushbutton flag. */
            g_sw_press = false;

            /* Notify that user pushbutton is pressed. */
            APP_PRINT("\r\nUser Pushbutton Pressed\r\n");

            /* Read user LED pin. */
            err = R_IOPORT_PinRead(&g_ioport_ctrl, (bsp_io_port_pin_t)leds.p_leds[RESET_VALUE], &led_current_state);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_IOPORT_PinRead API failed **\r\n");

                /* Close external IRQ module. */
                intc_irq_deinit();
                APP_ERR_TRAP(err);
            }

            /* Reverse LED pin state. */
            led_current_state ^= BSP_IO_LEVEL_HIGH;

            /* Toggle user LED. */
            err = R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)leds.p_leds[RESET_VALUE], led_current_state);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_IOPORT_PinWrite API failed **\r\n");

                /* Close external IRQ module. */
                intc_irq_deinit();
                APP_ERR_TRAP(err);
            }
            if (BSP_IO_LEVEL_HIGH == led_current_state)
            {
                /* Print LED Pin state. */
                APP_PRINT("LED State: High{ON}\r\n");
            }
            else
            {
                /* Print LED Pin state. */
                APP_PRINT("LED State: Low{OFF}\r\n");
            }
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_intc_irq_ep)
 **********************************************************************************************************************/
