/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "mtu3_phase_count_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_mtu3_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    volatile fsp_err_t err =  FSP_SUCCESS;

    static timer_status_t s_timer_status;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Array to store input from RTT terminal */
    char rtt_input_Command[BUFFER_SIZE_DOWN];
    char rtt_input_data[DATA_LENGTH_BYTE * 2];

    /* Indicates whether the input string is a valid hexadecimal address */
    bool data_check_result = false;

    /* Holds the converted binary data from the validated hexadecimal input string */
    uint8_t conversionData[DATA_LENGTH_BYTE] = {0x00,0x00};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* MTU3 driver initialization and start Phase Count */
    err = init_mtu3_driver();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** MTU3 driver initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* menu printed on the Console */
    APP_PRINT(MENU);

    while (true)
    {
        /* Check for input data from RTT terminal, once data is available read. */
        if (APP_CHECK_DATA)
        {
            memset(rtt_input_Command, '\0', sizeof(rtt_input_Command));

            /* Reading complete input instead of 1 byte to avoid processing of successive extra bytes entered */
            APP_READ(rtt_input_Command);
            if ('\0' != rtt_input_Command[1])
            {
                APP_PRINT("\r\nInvalid input length. Please enter only one character.\n");
            }
            else
            {
                switch (rtt_input_Command[0])
                {
                    /* Get operation */
                    case 'g':
                    {
                        APP_PRINT("\r\nGet(g) executed.\n");
                        err = R_MTU3_StatusGet(&g_timer_ctrl, &s_timer_status);
                        
                        /* Handle error */
                        if (FSP_SUCCESS != err)
                        {
                            APP_ERR_PRINT("\r\n ** R_MTU3_StatusGet API FAILED ** \r\n");
                            APP_ERR_TRAP(err);
                        }
                        APP_PRINT("%x\n", (unsigned int)s_timer_status.counter);    /* cast to unsigned int type */
                        break;
                    }

                    /* Set operation */
                    case 's':
                    {
                        /* Input data */
                        APP_PRINT("\r\nEnter the Value:\n");
                        while (!APP_CHECK_DATA)
                        {
                            ; /* wait for rtt_input_data value */
                        }
                        memset(rtt_input_data, RESET_VALUE, sizeof(rtt_input_data));
                        APP_READ(rtt_input_data);

                        data_check_result = input_data_check(rtt_input_data, conversionData);
                        if (data_check_result)
                        {
                            APP_PRINT("\r\nSet(s) executed.\n");

                            /* cast to uint32_t type */
                            s_timer_status.counter = (uint32_t)((conversionData[0] << 24) | (conversionData[1] << 16));
                            s_timer_status.counter >>= 16;

                            err = R_MTU3_Stop(&g_timer_ctrl);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n ** R_MTU3_Stop API FAILED ** \r\n");
                                APP_ERR_TRAP(err);
                            }
                            err = R_MTU3_CounterSet(&g_timer_ctrl, s_timer_status.counter);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n ** R_MTU3_CounterSet API FAILED ** \r\n");
                                APP_ERR_TRAP(err);
                            }
                            err = R_MTU3_Start(&g_timer_ctrl);

                            /* Handle error */
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("\r\n ** R_MTU3_Start API FAILED ** \r\n");
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("%x\n", (unsigned int)s_timer_status.counter);    /* cast to unsigned int type */
                        }
                        break;
                    }

                    /* Reset operation */
                    case 'r':
                    {
                        err = R_MTU3_Reset(&g_timer_ctrl);

                        /* Handle error */
                        if (FSP_SUCCESS != err)
                        {
                            APP_ERR_PRINT("\r\n ** R_MTU3_Reset API FAILED ** \r\n");
                            APP_ERR_TRAP(err);
                        }
                        APP_PRINT("\r\nReset(r) executed.\n");
                        break;
                    }
                    default:
                    {
                        APP_PRINT("\r\nCommand Error!\n");
                        break;
                    }
                }
            }
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
 #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_mtu3_ep)
 **********************************************************************************************************************/
