/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "i2c_pmic.h"
#include "common_utils.h"
#include "gpt_timer.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/* Value to validate open state of timer instances */
extern uint8_t g_timer_open_state;
extern bool volatile g_one_shot_expired;

/***********************************************************************************************************************
 * @addtogroup r_gpt_ep
 * @{
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * main() is generated by the Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err                           = FSP_SUCCESS;
    uint8_t rByte[BUF_SIZE]                 = {INITIAL_VALUE};
    uint32_t read_data                      = RESET_VALUE;
    uint32_t gpt_desired_duty_cycle_percent = RESET_VALUE;
    uint32_t gpt_desired_period_ms          = RESET_VALUE;
    uint64_t period_counts                  = RESET_VALUE;
    uint32_t p0clk_freq_hz                  = RESET_VALUE;
    int32_t  one_shot_timeout               = INT32_MAX;
    fsp_pack_version_t version;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
        version.version_id_b.patch);

    APP_PRINT(EP_INFO);

    /* Print Menu option of GPT timer */
    APP_PRINT(MENU);
    while (true)
    {
        /* Process input only when User has provided one */
        if (APP_CHECK_DATA)
        {
            /* Read First byte of data provided by user */
            APP_READ(rByte);

            /* Conversion from input string to integer value */
            read_data = (uint32_t) (atoi((char *)rByte));
            switch (read_data)
            {
                case PERIODIC_MODE_TIMER:
                {
                    /* Check the status of GPT timer in PWM mode */
                    if (PWM_MODE == g_timer_open_state)
                    {
                        /* Close PWM Timer instance */
                        deinit_gpt_timer(&g_timer_pwm_ctrl);
                        APP_PRINT("PWM Timer instance closed, Start Periodic Timer instance\r\n");
                    }

                    /* Check the status of GPT timer in One-shot mode */
                    if (ONE_SHOT_MODE == g_timer_open_state)
                    {
                        /* Close One-shot GPT Timer instance */
                        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
                        APP_PRINT("One-shot GPT Timer instance closed, Start Periodic Timer instance\r\n");
                    }

                    APP_PRINT("\r\nEnter the desired period in millisecond\r\n");
                    gpt_desired_period_ms = process_input_data();

                    /* Get the source clock frequency (in Hz) */
                    p0clk_freq_hz = R_FSP_SystemClockHzGet(FSP_PRIV_CLOCK_P0CLK);
                    p0clk_freq_hz >>= (uint32_t)(g_timer_periodic_cfg.source_div); /* Cast to uint32_t */

                    /* Convert period to P0CLK counts so it can be set in hardware. */
                    period_counts = (uint64_t)((gpt_desired_period_ms *(CLOCK_TYPE_SPECIFIER * p0clk_freq_hz))
                            / TIMER_UNITS_MILLISECONDS);

                    /* Validate Period Count based on user input (time period in ms) */
                    if (GPT_MAX_PERIOD_COUNT < period_counts)
                    {
                        APP_ERR_PRINT("\r\n** Invalid input, Desired period is out of range. **\r\n");
                    }
                    else
                    {
                        /* Check the status of GPT timer in Periodic mode */
                        if (PERIODIC_MODE != g_timer_open_state)
                        {
                            /* Initialize Periodic Timer */
                            err = init_gpt_timer(&g_timer_periodic_ctrl, &g_timer_periodic_cfg, PERIODIC_MODE_TIMER);
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("** init_gpt_timer failed **\r\n");
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("Opened Timer in Periodic Mode\r\n");

                            /* Start Periodic Timer */
                            err = start_gpt_timer(&g_timer_periodic_ctrl);
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("** start_gpt_timer failed **\r\n");

                                /* Close Periodic Timer instance */
                                deinit_gpt_timer(&g_timer_periodic_ctrl);
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("Started Timer in Periodic Mode\r\n");
                        }
                        else
                        {
                            APP_PRINT("Periodic Timer already started, Update Timer Period to : %d\r\n",
                                        gpt_desired_period_ms);
                        }

                        /* Period Set API set the desired period counts on the user LED */
                        err = R_GPT_PeriodSet(&g_timer_periodic_ctrl, (uint32_t)period_counts);
                        if (FSP_SUCCESS != err)
                        {
                            /* GPT Timer PeriodSet failure message */
                            APP_ERR_PRINT("\r\nR_GPT_PeriodSet API failed");

                            /* Close Periodic Timer instance */
                            deinit_gpt_timer(&g_timer_periodic_ctrl);
                            APP_ERR_TRAP(err);
                        }
                    }
                    break;
                }

                case PWM_MODE_TIMER:
                {
                    /* Check the status of GPT timer in Periodic mode */
                    if (PERIODIC_MODE == g_timer_open_state)
                    {
                        /* Close Periodic Timer instance */
                        deinit_gpt_timer(&g_timer_periodic_ctrl);
                        APP_PRINT("Periodic Timer instance closed, Start PWM Timer instance\r\n");
                    }

                    /* Check the status of GPT timer in One-shot mode */
                    if (ONE_SHOT_MODE == g_timer_open_state)
                    {
                        /* Close One-shot Timer instance */
                        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
                        APP_PRINT("One-shot Timer Instance Closed, Start PWM Timer Instance\r\n");
                    }

                    APP_PRINT("\r\nEnter the desired Duty Cycle in percentage of range 0 - 100:\r\n");
                    gpt_desired_duty_cycle_percent = process_input_data();

                    /* Validate Duty cycle percentage */
                    if (GPT_MAX_PERCENT < gpt_desired_duty_cycle_percent)
                    {
                        APP_ERR_PRINT("\r\n** Invalid input, Desired Duty Cycle is out of range. **\r\n");
                    }
                    else
                    {
                        /* Check the status of GPT timer in PWM mode */
                        if (PWM_MODE != g_timer_open_state)
                        {
                            /* We got valid input, initialize PWM timer */
                            err = init_gpt_timer(&g_timer_pwm_ctrl, &g_timer_pwm_cfg, PWM_MODE_TIMER);
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("** init_gpt_timer failed **\r\n");
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("Opened Timer in PWM Mode\r\n");

                            /* Start PWM Timer */
                            err = start_gpt_timer(&g_timer_pwm_ctrl);
                            if (FSP_SUCCESS != err)
                            {
                                APP_ERR_PRINT("** start_gpt_timer failed **\r\n");

                                /* Close PWM Timer instance */
                                deinit_gpt_timer(&g_timer_pwm_ctrl);
                                APP_ERR_TRAP(err);
                            }
                            APP_PRINT("Started Timer in PWM Mode\r\n");
                        }
                        else
                        {
                            /* Print Duty cycle on RTT, when PWM Timer already started */
                            APP_PRINT("PWM Timer already started, Update duty cycle to: %d\r\n",
                                        gpt_desired_duty_cycle_percent);
                        }

                        /* Set Duty cycle of PWM timer */
                        err = set_timer_duty_cycle((uint8_t)gpt_desired_duty_cycle_percent);
                        if (FSP_SUCCESS != err)
                        {
                            /* GPT Timer DutyCycleSet failure message */
                            APP_ERR_PRINT("\r\n** set_timer_duty_cycle failed **\r\n");

                            /* Close PWM Timer instance */
                            deinit_gpt_timer(&g_timer_pwm_ctrl);
                            APP_ERR_TRAP(err);
                        }
                    }
                    break;
                }
                case ONE_SHOT_MODE_TIMER :
                {
                    /* Check the status of GPT timer in Periodic mode */
                    if (PERIODIC_MODE == g_timer_open_state)
                    {
                        /* Close Periodic Timer instance */
                        deinit_gpt_timer(&g_timer_periodic_ctrl);
                        APP_PRINT("Periodic Timer Instance Closed, Start One-shot Timer Instance\r\n");
                    }

                    /* Check the status of GPT timer in PWM mode */
                    if (PWM_MODE == g_timer_open_state)
                    {
                        /* Close PWM Timer instance */
                        deinit_gpt_timer(&g_timer_pwm_ctrl);
                        APP_PRINT("PWM Timer Instance Closed, Start One-shot Timer Instance\r\n");
                    }

                    /* Check the status of GPT timer in One-shot mode */
                    if (ONE_SHOT_MODE == g_timer_open_state)
                    {
                        /* Close One-shot Timer instance */
                        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
                        APP_PRINT("One-shot Timer instance closed, If already opened\r\n");
                    }

                    /* Initialize One-shot Timer */
                    err = init_gpt_timer(&g_timer_one_shot_mode_ctrl, &g_timer_one_shot_mode_cfg, ONE_SHOT_MODE_TIMER);
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT("** init_gpt_timer failed **\r\n");
                        APP_ERR_TRAP(err);
                    }
                    APP_PRINT("Opened Timer in One-shot Mode\r\n");

                    /* Start One-shot Timer */
                    err = start_gpt_timer(&g_timer_one_shot_mode_ctrl);
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT("** start_gpt_timer failed **\r\n");

                        /* Close One-shot Timer instance */
                        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
                        APP_ERR_TRAP(err);
                    }
                    APP_PRINT("Started Timer in One-shot Mode\r\n");

                    /* Wait for One-shot mode timer to expire. */
                    while (true != g_one_shot_expired)
                    {
                        /* Start checking for time out to avoid infinite loop */
                        --one_shot_timeout;
                        if (RESET_VALUE == one_shot_timeout)
                        {
                            /* We have reached to a scenario where One-shot event did not occur */
                            APP_ERR_PRINT("Callback event not received during One-Shot operation\r\n");
                            break;
                        }
                    }
                    if (true == g_one_shot_expired)
                    {
                        APP_PRINT("\r\n Timer expired in One-Shot Mode\r\n");
                    }
                    g_one_shot_expired = false;
                    break;
                }
                default:
                {
                    APP_PRINT("\r\nInvalid menu option selected\r\n");
                    break;
                }
            }
            read_data = RESET_VALUE;

            /* Reset buffer */
            memset(rByte, INITIAL_VALUE, BUF_SIZE);

            /* Print menu option of GPT timer */
            APP_PRINT(MENU);
        }
        else
        {
            /* Do nothing */;
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at.
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* Allow access to IP beyond AXI */
        pd_all_on_postproc_axi();
        pd_all_on_postproc();
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_gpt_ep)
 **********************************************************************************************************************/
