/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "spi_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_spi_ep
 * @{
 **********************************************************************************************************************/
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);

FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    uint8_t converted_rtt_input = RESET_VALUE;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Banner information */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize SPI driver */
    err = spi_init();

    if (FSP_SUCCESS != err)
    { 
        /* SPI module initialization failed */
        APP_PRINT("\r\n** spi_init failed **\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n** SPI_B initialization sucessfully **\r\n");
    }

    /* Menu for user selection */
    APP_PRINT("\r\nSelect from the below menu options\r\n");
    APP_PRINT("\r\nPress 1 for Write() to Pmod SF3");
    APP_PRINT("\r\nPress 2 for Read() from Pmod SF3");
    APP_PRINT("\r\nPress 3 to Exit\r\n");

    while (EXIT != converted_rtt_input)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            converted_rtt_input = (uint8_t) atoi ((char*) rByte);

            switch (converted_rtt_input)
            {
                case WRITE:
                    err = spi_write();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** spi_write failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** SPI_B WRITE to Pmod SF3 demo successful **\r\n");
                    }
                break;
                case READ:
                    err = spi_read();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** spi_read failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** SPI_B READ from Pmod SF3 demo successful **\r\n");
                    }
                break;
                case EXIT:
                    err = spi_exit_demo();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** spi_exit_demo failed **\r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
    {
                        APP_PRINT("** SPI_B EXIT demo successful **\r\n");
    }
                break;
                default:
                    /* Menu for user selection */
                    APP_PRINT("\r\nSelect from the below menu options\r\n");
                    APP_PRINT("\r\nPress 1 for Write() to Pmod SF3");
                    APP_PRINT("\r\nPress 2 for Read() from Pmod SF3");
                    APP_PRINT("\r\nPress 3 to Exit\r\n");
                break;
            }

            if ((WRITE <= converted_rtt_input) && (EXIT > converted_rtt_input))
            {
                APP_PRINT("\r\nEnter any other key to go back to the main menu\r\n");
            }
        }
    }

    APP_PRINT(RTT_CTRL_TEXT_BRIGHT_CYAN "\r\nExiting SPI_B demo....\r\n" RTT_CTRL_RESET);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

        /* Configure pins */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_spi_ep)
 **********************************************************************************************************************/
