/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "xspi_ospi_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_xspi_ospi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

const uint8_t g_src[DATA_SIZE] =
{
    0x33, 0x33, 0x33, 0x33, 0xBB, 0xFE, 0xEE, 0xF1, 0x34, 0x34, 0x34, 0x34, 0xBC, 0xFF, 0xEF, 0xF2,
    0x35, 0x35, 0x35, 0x35, 0xBD, 0xFF, 0xEE, 0xF1, 0x36, 0x36, 0x36, 0x36, 0xBC, 0xFF, 0xEF, 0xF2,
    0x37, 0x37, 0x37, 0x37, 0xBF, 0x01, 0xEE, 0xF1, 0x38, 0x38, 0x38, 0x38, 0xBA, 0x1F, 0x6F, 0xF3
};

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Open the OSPI instance */
    err = R_XSPI_OSPI_Open(&g_ospi0_ctrl, &g_ospi0_cfg);
    if (FSP_SUCCESS != err)
    {   /* OSPI instance open failed */
        APP_PRINT("\r\n ** R_XSPI_OSPI OPEN FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Set DTR-OPI Enable in configuration register 2 (volatile) */
    ospi_set_DTR_OPI_Mode_enable();

    /*---------- Chip Erase ----------*/
    /*
    err = R_XSPI_OSPI_Erase(&g_ospi0_ctrl, (uint8_t *)OSPI_DEVICE_START_ADDRESS, SPI_FLASH_ERASE_SIZE_CHIP_ERASE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CHIP ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[CHIP ERASE] done.\r\n");
    }
    */

    /*---------- Sector Erase ----------*/
    uint8_t  * const erase_addr = (uint8_t *)(OSPI_DEVICE_START_ADDRESS + WRITE_START_ADDRESS);
    uint32_t  const erase_len   = SECTOR_ERASE_SIZE;
    APP_PRINT("[SECTOR ERASE] sector @0x%08X, length %uB\r\n", erase_addr, (unsigned) erase_len);   /* cast to unsigned */
    err = R_XSPI_OSPI_Erase(&g_ospi0_ctrl, erase_addr, erase_len);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[SECTOR ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[SECTOR ERASE] done.\r\n");
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_erase;
    do
    {
         (void)R_XSPI_OSPI_StatusGet(&g_ospi0_ctrl, &status_erase);
    } while (true == status_erase.write_in_progress);
    APP_PRINT("[ERASE] done\r\n");

    /*---------- Direct transfer (WRITE) ----------*/
    spi_flash_direct_transfer_t ospi_test_direct_transfer_write_enable = {0};
    ospi_test_direct_transfer_write_enable.command        = 0x06F9;  /* Write Enable */
    ospi_test_direct_transfer_write_enable.command_length = 2U;
    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &ospi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER WRITE] successfully\r\n");
    }
    spi_flash_direct_transfer_t ospi_test_direct_transfer_write =
    {
        .command        = 0x12EDU,  /* PP instruction (DTR-OPI Mode) */
        .address        = 0x00001114U,
        .data           = 0x1114U,
        .command_length = 2U,
        .address_length = 4U,
        .data_length    = 2U,
        .dummy_cycles   = 0U
    };
    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &ospi_test_direct_transfer_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PAGE PROGRAM] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PAGE PROGRAM] ADDR=0x%08X LEN=%u data=0x%04X\r\n",
                  (unsigned) ospi_test_direct_transfer_write.address,
                  (unsigned) ospi_test_direct_transfer_write.data_length,
                  (unsigned) (ospi_test_direct_transfer_write.data & 0xFFFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_OSPI_StatusGet(&g_ospi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /*---------- Direct transfer (READ) ----------*/
    spi_flash_direct_transfer_t ospi_test_direct_transfer_read =
    {
        .command        = 0xEE11U,  /* 8DTRD(DTR-OPI) instruction */
        .address        = 0x00001114U,
        .data           = 0U,
        .command_length = 2U,
        .address_length = 4U,
        .data_length    = 2U,
        .dummy_cycles   = 10U
    };
    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &ospi_test_direct_transfer_read, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER READ] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER READ] CMD=0x%04X addr=0x%08X dummy=%u LEN=%u -> 0x%04X\r\n",
                  (unsigned) ospi_test_direct_transfer_read.command,
                  (unsigned) ospi_test_direct_transfer_read.address,
                  (unsigned) ospi_test_direct_transfer_read.dummy_cycles,
                  (unsigned) ospi_test_direct_transfer_read.data_length,
                  (unsigned) ospi_test_direct_transfer_read.data);
    }

    /*---------- Verify Write data = Read data? ----------*/
    if (ospi_test_direct_transfer_read.data != ospi_test_direct_transfer_write.data)
    {
        APP_ERR_PRINT("[VERIFY] mismatch: wrote=0x%02X read=0x%02X\r\n",
                      ospi_test_direct_transfer_write.data, ospi_test_direct_transfer_read.data);
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    else
    {
        APP_PRINT("[VERIFY] direct transfer OK\r\n");
    }

    /*---------- Read data using memory-mapping mode ----------*/
    uint32_t read_buffer = *(uint16_t *)(OSPI_DEVICE_START_ADDRESS - 0x20000000 + ospi_test_direct_transfer_write.address);
    APP_PRINT("[MAP-READ] ADDR=0x%08X -> 0x%02X\r\n",
              (unsigned) ospi_test_direct_transfer_write.address, (unsigned) read_buffer);

    /*---------- Verify Write data = Read data? ----------*/
    if (read_buffer != ospi_test_direct_transfer_write.data)
    {
        APP_ERR_PRINT("[VERIFY] mapped mismatch: w=0x%04X r=0x%04X\r\n",
                      (unsigned)(ospi_test_direct_transfer_write.data & 0xFFFFu),
                      (unsigned) read_buffer);    /* cast to unsigned*/
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    APP_PRINT("[VERIFY] mapped read OK\r\n");

    /*---------- Write Data via write API ----------*/
    uint8_t * dest = (uint8_t *)(OSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_START_ADDRESS);  /* xSPI0_CS0 memory, non-cache area use.*/
    err = R_XSPI_OSPI_Write(&g_ospi0_ctrl, g_src, dest, DATA_SIZE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE] OK\r\n");
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write2;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_OSPI_StatusGet(&g_ospi0_ctrl, &status_write2);
    } while (true == status_write2.write_in_progress);
    APP_PRINT("[WAIT] ready\r\n");

    /*---------- Verify Write data = Read data? ----------*/
    for (uint8_t i = 0; i < DATA_SIZE / 2; i++)
    {
        uint16_t dest_data = *((uint16_t *)(OSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_START_ADDRESS) + i);   /* cast to uint16_t*/
        uint16_t src_data = *((uint16_t *)g_src + i);   /* cast to uint16_t*/
        if (src_data != dest_data)
        {
            APP_ERR_PRINT("[VERIFY] mismatch @+%u: w=0x%04X r=0x%04X\r\n",
                          (unsigned) i, (unsigned) src_data, (unsigned) dest_data);    /* cast to unsigned*/
            APP_ERR_TRAP(FSP_ERR_ASSERTION);
        }
    }
    APP_PRINT("[VERIFY] write API OK\r\n");

    /* Close the application */
    APP_PRINT("[DONE]\r\n");
    while (1);
}

/***********************************************************************************************************************
 * @brief     Enable DTR-OPI mode on the OSPI device and switch the controller to 8D-8D-8D.
 * @param[in] None
 * @return    None
 **********************************************************************************************************************/
void ospi_set_DTR_OPI_Mode_enable(void)
{
    /* For following settings, temporary set protocol 1S-1S-1S */
    R_XSPI_OSPI_SpiProtocolSet(&g_ospi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*--------------- Write Enable(WE) (06h) ---------------*/
    spi_flash_direct_transfer_t ospi_test_direct_transfer_WE2 = {0};
    ospi_test_direct_transfer_WE2.command        = 0x06U;
    ospi_test_direct_transfer_WE2.command_length = 1U;
    fsp_err_t err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &ospi_test_direct_transfer_WE2, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE ENABLE] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE ENABLE] info: CMD=0x%02X\r\n",
                  (unsigned) ospi_test_direct_transfer_WE2.command);    /* cast to unsigned */
    }

    /*--------------------------------------------------------------*/

    /*--------------- Write Configuration register(WRCR2) (72h) ---------------*/
    uint32_t write_data = 0x02; /* Set DTR OPI Enable */
    spi_flash_direct_transfer_t direct_command_WRCR2_2 = {0};
    direct_command_WRCR2_2.command        = 0x72U;
    direct_command_WRCR2_2.address        = 0x00000000U,
    direct_command_WRCR2_2.command_length = 1U;
    direct_command_WRCR2_2.address_length = 4U;
    direct_command_WRCR2_2.data_length    = 1U;
    direct_command_WRCR2_2.data = write_data;

    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &direct_command_WRCR2_2, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE CONFIGURE REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE CONFIGURE REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                  (unsigned) direct_command_WRCR2_2.command,
                  (unsigned) direct_command_WRCR2_2.data_length,
                  (unsigned) (direct_command_WRCR2_2.data & 0xFFU));
    }

    /*--------------------------------------------------------------*/

    /* Change protocol settings from 1S-1S-1S to 8D-8D-8D. */
    R_XSPI_OSPI_SpiProtocolSet(&g_ospi0_ctrl, SPI_FLASH_PROTOCOL_8D_8D_8D);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PROTOCOL] Failed to set 8D-8D-8D: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PROTOCOL] 8D-8D-8D enabled\r\n");
    }

    /*--------------- Write Enable(WE) (06h) ---------------*/
    spi_flash_direct_transfer_t ospi_test_direct_transfer_WE1 = {0};
    ospi_test_direct_transfer_WE1.command        = 0x06F9U;
    ospi_test_direct_transfer_WE1.command_length = 2U;
    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &ospi_test_direct_transfer_WE1, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE ENABLE] DirectTransfer (after protocol) failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE ENABLE] info (after protocol): CMD=0x%04X\r\n",
                      (unsigned) ospi_test_direct_transfer_WE1.command);    /* cast to unsigned */
    }

    /*--------------------------------------------------------------*/

    /*--------------- Write Configuration register(WRCR2) (72h) ---------------*/
    write_data = 0x05; /* Set DC[2:0] = 0x05 (Number of Dummy cycle = 10) */
    spi_flash_direct_transfer_t direct_command_WRCR2_1 = {0};
    direct_command_WRCR2_1.command        = 0x728DU;
    direct_command_WRCR2_1.address        = 0x00000300U;
    direct_command_WRCR2_1.command_length = 2U;
    direct_command_WRCR2_1.address_length = 4U;
    direct_command_WRCR2_1.data_length    = 1U;
    direct_command_WRCR2_1.data = write_data;

    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &direct_command_WRCR2_1, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE CONGIGURE REGISTER] DirectTransfer (after protocol) failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE CONGIGURE REGISTER] info (after protocol): CMD=0x%04X, LEN=%u -> 0x%02X\r\n",
                      (unsigned) direct_command_WRCR2_1.command,
                      (unsigned) direct_command_WRCR2_1.data_length,
                      (unsigned) (direct_command_WRCR2_1.data & 0xFFU));
    }

    /*--------------------------------------------------------------*/

    /*---------------- Read Configuration register 2(RDCR2) (71h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDCR2_2 = {0};
    direct_command_RDCR2_2.command        = 0x718EU;
    direct_command_RDCR2_2.address        = 0x00000300U;
    direct_command_RDCR2_2.command_length = 2U;
    direct_command_RDCR2_2.address_length = 4U;
    direct_command_RDCR2_2.data_length    = 1U;
    direct_command_RDCR2_2.dummy_cycles   = 10U;

    err = R_XSPI_OSPI_DirectTransfer(&g_ospi0_ctrl, &direct_command_RDCR2_2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ CONFIGURE REGISTER] DirectTransfer (after protocol) failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ CONFIGURE REGISTER] info (after protocol): CMD=0x%04X, LEN=%u -> 0x%02X\r\n",
                      (unsigned) direct_command_RDCR2_2.command,
                      (unsigned) direct_command_RDCR2_2.data_length,
                      (unsigned) (direct_command_RDCR2_2.data & 0xFFU));
    }

    /*--------------------------------------------------------------*/
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_xspi_ospi_ep)
 **********************************************************************************************************************/

