/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright (c) 2025 - 2026 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/
#include "common_utils.h"
#include "timer_setup.h"
#include "ext_irq_setup.h"

/***********************************************************************************************************************
 * @addtogroup r_wdt_ep
 * @{
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * External global variables
 **********************************************************************************************************************/

/* LED Structure used to blink Pmod LED */
extern bsp_leds_t g_bsp_leds;

extern volatile uint8_t g_timer_overflow_counter;

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * Private function declarations
 **********************************************************************************************************************/

/* The function used to read Tera Term input and proceed */
static fsp_err_t read_input_from_teraterm (void);

/* The function used to enable WDT in debug mode */
static void enable_wdt_count_in_debug_mode (void);

/* The function used to check if reset is caused by WDT or not */
static void check_reset_status (void);

/***********************************************************************************************************************
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* If no LEDs are available, print an error message and halt */
    if (RESET_VALUE == g_bsp_leds.led_count)
    {
        APP_PRINT("No available LEDs found\r\n");
        APP_ERR_TRAP(FSP_ERR_UNSUPPORTED);
    }

    check_reset_status();

    /* Initialize GTM in Periodic mode */
    err = init_gtm_module();
    if (FSP_SUCCESS != err)
    {
        /* Timer initialization failed */
        APP_ERR_PRINT("** init_gtm_module failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initialize External IRQ */
    err = init_irq_module();
    if (FSP_SUCCESS != err)
    {
        /* External IRQ initialization failed, cleanup the timer initialization */
        APP_ERR_PRINT("** init_irq_module failed **\r\n");
        deinit_gtm_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for user selection */
    APP_PRINT("\r\nEnter 1 to enable WDT\r\n");
    APP_PRINT("\r\nUser input:\r\n");

    while (true)
    {
        /* Process input only when the user has provided one */
        if (APP_CHECK_DATA)
        {
            err = read_input_from_teraterm();
            if (FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ modules */
                deinit_gtm_module();
                deinit_irq_module();
                APP_ERR_TRAP(err);
            }
        }

        /* For every 3 seconds, Tera Term prints WDT refresh message.
         * This is done to avoid continuous print messages on Tera Term. */
        if (WDT_REFRESH_COUNTER_VALUE == g_timer_overflow_counter)
        {
            g_timer_overflow_counter = RESET_VALUE;
            APP_PRINT("WDT counter refreshed\r\n");
        }
    }
}

/***********************************************************************************************************************
 * @brief       This function is called to read user input from Tera Term using UART, and handle the error internally
 *              with proper message. The application handles the rest.
 * @param[in]   None.
 * @retval      FSP_SUCCESS     Upon successful operation.
 * @retval      Any other error code apart from FSP_SUCCESS  Unsuccessful to perform operation.
 **********************************************************************************************************************/
fsp_err_t read_input_from_teraterm(void)
{
    /* Error status */
    fsp_err_t err = FSP_SUCCESS;

    /* Variable to store user input */
    uint8_t rByte[BUFFER_SIZE] = {RESET_VALUE};
    uint8_t user_data = RESET_VALUE;

    /* Read first byte of data provided by the user */
    APP_READ(rByte);

    user_data = (uint8_t) atoi((char *)&rByte);

    switch (user_data)
    {
        case ENABLE_WDT:
        {
            /* Enable WDT to count and generate NMI or reset when the debugger (J-Link) is connected */
            enable_wdt_count_in_debug_mode();

            /* Open WDT. For every GTM timeout, WDT will get refreshed. */
            err = R_WDT_Open(&g_wdt_ctrl, &g_wdt_cfg);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_WDT_Open API failed **\r\n");
                return err;
            }

            /* Start GTM timer in Periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** timer_start failed **\r\n");
                return err;
            }

            /* Enable External IRQ */
            err = enable_irq_module();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** enable_irq_module failed **\r\n");
                return err;
            }

            /* Print message to indicate the user about application status */
            APP_PRINT("WDT initialized, GTM timer started\r\n");
            APP_PRINT("To stop WDT counter from refreshing, press the push button\r\n");
            break;
        }
        default:
        {
            /* Menu for user selection */
            APP_PRINT("Invalid input\r\n");
            APP_PRINT("Please provide input from below option\r\n");
            APP_PRINT("Enter 1 to enable WDT\r\n");
            APP_PRINT("User input:  \r\n");
            break;
        }
    }
    user_data = RESET_VALUE;
    return err;
}

/***********************************************************************************************************************
 * @brief       This function is called to enable WDT counter in debug mode.
 *              Enables WDT counter to count in debug mode.
 * @param[in]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void enable_wdt_count_in_debug_mode(void)
{
    /* As per hardware manual's section 6.3.5:- Clear this bit to Stop WDT0 from counting in debug mode */
    R_SYSC->SYS_WDT0_CTRL_b.WDTSTOPMASK = RESET_VALUE;
}

/***********************************************************************************************************************
 * @brief       This function is called to check whether reset is caused by WDT.
 *              Check if reset caused by WDT or not.
 * @param[in]   None.
 * @retval      None.
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    /* Check if reset was caused by the WDT? If it was, turn on LED to indicate WDT reset triggered. */
    if (R_CPG->CPG_WDTOVF_RST_b.WDTOVF0 == R_CPG_CPG_WDTOVF_RST_WDTOVF0)
    {
        /* Clear the flag once read the value */
        R_CPG->CPG_WDTOVF_RST = R_CPG_CPG_WDTOVF_RST_WDTOVF0_Msk;

        /* Turn ON LED */
        R_BSP_PinWrite((bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_HIGH);

        APP_PRINT("\r\n************************ WDT reset detected ************************\r\n");
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_wdt_ep)
 **********************************************************************************************************************/
