/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "uart_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_sci_uart_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

uint8_t g_receive_buffer[TEXT_LENGTH];

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initializing UART */
    err = uart_initialize();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** UART driver initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    err = uart_print_user_msg("\r\nHello World.\r\n");

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** UART WRITE FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    while (1)
    {
        err = uart_print_user_msg("\r\nUser input: ");

        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT("\r\n ** UART WRITE FAILED ** \r\n");
            APP_ERR_TRAP(err);
        }

        err = uart_get_user_msg((char *)g_receive_buffer);   /* cast to char * type */

        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT("\r\n ** UART READ FAILED ** \r\n");
            APP_ERR_TRAP(err);
        }

        err = uart_print_user_msg((char *)g_receive_buffer);    /* cast to char * type */

        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT("\r\n ** UART WRITE FAILED ** \r\n");
            APP_ERR_TRAP(err);
        }

        /* Reset receive buffer */
        memset(g_receive_buffer, 0, TEXT_LENGTH);

        /* Check transfer settings */
        while ((NULL == g_transfer0_ctrl.p_cfg->p_info->p_src) || (NULL == g_transfer0_ctrl.p_cfg->p_info->p_dest))
        {
            ;   /* Idle loop - waiting for transfer configuration */
        }
        while ((NULL == g_transfer1_ctrl.p_cfg->p_info->p_src) || (NULL == g_transfer1_ctrl.p_cfg->p_info->p_dest))
        {
            ;   /* Idle loop - waiting for transfer configuration */
        }
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        ;/* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_sci_uart_ep)
 **********************************************************************************************************************/
