/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "usb_hcdc_ep.h"

/***********************************************************************************************************************
 * @addtogroup usb_pcdc_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

#define DATA_LEN                    (512)
#define USB_DEVICE_ADDRESS_1        (1)

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/
typedef struct
{
    uint8_t     bitmap[2];                   /* UART State bitmap */
    usb_setup_t setup;                       /* Class Specific Notification */
} serial_state_t;

/***********************************************************************************************************************
 * Private global variables and functions
 **********************************************************************************************************************/
serial_state_t        g_serial_state;             /* SerialState */

uint8_t               g_snd_buf[DATA_LEN+4];
uint8_t               g_rcv_buf[DATA_LEN+4];

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * @fn         hal_entry
 * @brief      hal_entry function.
 * @retval     None
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
                version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    usb_status_t     event;

    usb_event_info_t event_info;

    uint16_t i;

    err = g_usb_on_usb.open(&g_basic0_ctrl, &g_basic0_cfg);

    /* Error Handle */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nError in initializing USB Host CDC\r\n");
        APP_ERR_TRAP (err);
    }

    while (1)
    {
        /* Get USB event data */
        err = g_usb_on_usb.eventGet(&event_info, &event);

        /* Error Handle */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT ("\r\nError in get events USB Host CDC\r\n");
            APP_ERR_TRAP (err);
        }
        /* Handle the received event (if any) */
        switch (event)
        {
            case USB_STATUS_CONFIGURED:

                /* Configure virtual UART settings */
                set_line_coding(&g_basic0_ctrl, event_info.device_address); /* CDC Class request "SetLineCoding" */
                break;

            case USB_STATUS_READ_COMPLETE:
                if (USB_CLASS_HCDC == event_info.type)
                {
                    /* Wait until the data is completely sent to the RTT Viewer */
                    while (SEGGER_RTT_GetAvailWriteSpace(0) != (BUFFER_SIZE_UP - 1))
                    {
                        ;
                    }

                    APP_PRINT("Received data :");
                    for (i = 0; i < DATA_LEN; i++)
                    {
                        APP_PRINT(" %d,", g_rcv_buf[i]);
                        if (255 == i)
                        {
                            APP_PRINT("\n");

                        }
                    }
                    APP_PRINT("\n");

                    if (event_info.data_size > 0)
                    {
                        /* Send the received data back to the connected peripheral */
                        err = g_usb_on_usb.write(&g_basic0_ctrl, g_snd_buf, event_info.data_size, USB_DEVICE_ADDRESS_1);

                        /* Handle Error */
                        if (FSP_SUCCESS != err)
                        {
                            handle_error (err, "**R_USB_Write API FAILED**");
                        }
                    }
                    else
                    {
                        /* Send the data reception request when the zero-length packet is received. */
                        err = g_usb_on_usb.read(&g_basic0_ctrl, g_rcv_buf, DATA_LEN, USB_DEVICE_ADDRESS_1);
                        
                        /* Handle Error */
                        if (FSP_SUCCESS != err)
                        {
                            handle_error (err,"**R_USB_Read API FAILED**");
                        }
                    }
                }
                else
                {
                    /* Control Class notification "SerialState" receive start */
                    err = g_usb_on_usb.read(&g_basic0_ctrl, (uint8_t *) &g_serial_state,
                                        USB_HCDC_SERIAL_STATE_MSG_LEN, USB_DEVICE_ADDRESS_1);

                    /* Handle Error */
                    if (FSP_SUCCESS != err)
                    {
                        handle_error (err,"**R_USB_Read API FAILED**");
                    }
                }
                break;

            case USB_STATUS_WRITE_COMPLETE:
                if (event_info.data_size > 0)
                {
                    /* Start receive operation */
                    err = g_usb_on_usb.read(&g_basic0_ctrl, g_rcv_buf, DATA_LEN, USB_DEVICE_ADDRESS_1);

                    /* Handle Error */
                    if (FSP_SUCCESS != err)
                    {
                        handle_error (err,"**R_USB_Read API FAILED**");
                    }
                }
                break;
            case USB_STATUS_REQUEST_COMPLETE:
                if (USB_CDC_SET_LINE_CODING == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* Set virtual RTS/DTR signal state */

                    /* CDC Class request "SetControlLineState" */
                    set_control_line_state(&g_basic0_ctrl, event_info.device_address);
                }
                /* Check Complete request "SetControlLineState" */
                else if (USB_CDC_SET_CONTROL_LINE_STATE == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* Read back virtual UART settings */
                    get_line_coding(&g_basic0_ctrl, event_info.device_address); /* CDC Class request "SetLineCoding" */
                }
                else if (USB_CDC_GET_LINE_CODING == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* Now that setup is complete, start loopback operation */
                    APP_PRINT("\r\nSetup is complete, start loopback operation\n");
                    for (i = 0; i < DATA_LEN; i++)
                    {
                        g_snd_buf[i] = (uint8_t)i;   /* cast type */
                        APP_PRINT(" %d,", g_snd_buf[i]);
                        if (255 == i)
                        {
                            APP_PRINT("\n");
                        }
                    }
                    APP_PRINT("\n");

                    /* Wait until the data is completely sent to the RTT Viewer */
                    while (SEGGER_RTT_GetAvailWriteSpace(0) != (BUFFER_SIZE_UP - 1))
                    {
                        ;
                    }

                    err = g_usb_on_usb.write(&g_basic0_ctrl, g_snd_buf, DATA_LEN, USB_DEVICE_ADDRESS_1);

                    if (FSP_SUCCESS != err)
                    {
                        handle_error (err, "**R_USB_Write API FAILED**");
                    }
                }
                else
                {
                    /* Unsupported request */;
                }
                break;

            default:

                /* Other event */
                break;
        }
    }
}
/***********************************************************************************************************************
 * End of function: hal_entry
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
/***********************************************************************************************************************
 * End of function: R_BSP_WarmStart
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @} (end addtogroup usb_pcdc_ep)
 **********************************************************************************************************************/
