/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "shared_memory_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_shared_memory_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

static volatile uint32_t data_receive_flag = 0;

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    uint32_t offset;
    uint32_t transfer_length = SHARED_MEMORY_SIZE / 2;

    uint8_t transmit_buffer[SHARED_MEMORY_SIZE]        = {0};
    uint8_t receive_buffer[SHARED_MEMORY_SIZE]         = {0};
    uint8_t receive_expected_value[SHARED_MEMORY_SIZE] = {0};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    for (uint32_t i = 0; i < SHARED_MEMORY_SIZE; i++)
    {
        transmit_buffer[i] = (uint8_t) ~i;
        receive_expected_value[i] = (uint8_t) i;
    }

    /* Open the shared-memory driver. */
    err = R_SHARED_MEMORY_Open(&g_shared_memory0_ctrl, &g_shared_memory0_cfg);
    APP_PRINT("[CPU1] Open SHARED_MEMORY Driver...\r\n");
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CPU1] Open failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    APP_PRINT("[CPU1] Open: OK\r\n");

    /* Wait until the driver of CPU0 writes data. */
    APP_PRINT("[CPU1] Waiting IRQ from CPU0 ...\r\n");
    while (0 == data_receive_flag);
    data_receive_flag = 0;
    APP_PRINT("[CPU1] IRQ from CPU0 received\r\n");

    /* Read data from the shared memory. */
    offset = 0;
    APP_PRINT("[CPU1] Read(offset=%lu, len=%lu)\r\n",
              (unsigned long)offset, (unsigned long)transfer_length);
    err = R_SHARED_MEMORY_Read(&g_shared_memory0_ctrl, &(receive_buffer[0]), offset, transfer_length);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CPU1] Read failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }

    /* Write data to the shared memory. */
    offset = SHARED_MEMORY_SIZE / 2;
    APP_PRINT("[CPU1] Write(offset=%lu, len=%lu) -> IRQ to CPU0\r\n",
              (unsigned long)offset, (unsigned long)transfer_length);
    err = R_SHARED_MEMORY_Write(&g_shared_memory0_ctrl, &(transmit_buffer[0]), offset, transfer_length);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CPU1] Write failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }

    /* Compare between the received data and expected value. */
    if (0 != memcmp(receive_buffer, receive_expected_value, transfer_length))
    {
        APP_ERR_PRINT("[CPU1] Compare: MISMATCH\r\n");
        APP_ERR_TRAP(-1);
    }
    APP_PRINT("[CPU1] Compare: MATCH\r\n");

    /* Close the driver. */
    err = R_SHARED_MEMORY_Close(&g_shared_memory0_ctrl);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CPU1] Close failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    APP_PRINT("[CPU1] Close: done\r\n");

    while (1)
    {
    }
}

/***********************************************************************************************************************
 * This function is user callback function. It is called in the following situations:
 * - When R_SHARED_MEMORY_Open() of the counter driver is called while this driver is open.
 *   In this case, p_args->state is SHARED_MEMORY_STATE_READY_TO_WRITE.
 * - When R_SHARED_MEMORY_Read() of the counter driver is called.
 *   In this case, p_args->state is SHARED_MEMORY_STATE_READY_TO_READ_WRITE.
 *
 * @param[out]  p_args    Callback arguments
 **********************************************************************************************************************/
void shared_memory_callback (shared_memory_callback_args_t * p_args)
{
    if (SHARED_MEMORY_STATE_READY_TO_READ_WRITE == p_args->state)
    {
        data_receive_flag = 1;
    }
    else /* (SHARED_MEMORY_STATE_READY_TO_WRITE == p_args->state) */
    {
        /* Do nothing */
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_shared_memory_ep)
 **********************************************************************************************************************/
