/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "xspi_qspi_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_xspi_qspi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

uint8_t g_src[DATA_SIZE];

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Open the QSPI instance */
    err = R_XSPI_QSPI_Open(&g_qspi0_ctrl, &g_qspi0_cfg);
    if (FSP_SUCCESS != err)
    {   /* QSPI instance open failed */
        APP_PRINT("\r\n ** R_XSPI_QSPI OPEN FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /*---------- Chip Erase ----------*/
    /*
    err = R_XSPI_QSPI_Erase(&g_qspi0_ctrl, (uint8_t *)QSPI_DEVICE_START_ADDRESS, SPI_FLASH_ERASE_SIZE_CHIP_ERASE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[CHIP ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[CHIP ERASE] done.\r\n");
    }
    */

    /*---------- Sector Erase ----------*/
    err = R_XSPI_QSPI_Erase(&g_qspi0_ctrl, (uint8_t *)QSPI_DEVICE_START_ADDRESS, 4096);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[SECTOR ERASE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[SECTOR ERASE] done.\r\n");
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_erase;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_erase);
    } while (true == status_erase.write_in_progress);

    /*---------- Direct transfer (WRITE) ----------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06,  /* Write Enable */
    qspi_test_direct_transfer_write_enable.command_length = 1U,
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER WRITE] successfully\r\n");
    }
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write =
    {
        .command        = 0x02U,  /* PP instruction */
        .address        = 0x000234U,
        .data           = 0x12U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,
        .dummy_cycles   = 0U
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[PAGE PROGRAM] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[PAGE PROGRAM] ADDR=0x%08X LEN=%u data=0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_write.address,
                    (unsigned) qspi_test_direct_transfer_write.data_length,
                    (unsigned) (qspi_test_direct_transfer_write.data & 0xFFU));    /* cast to unsigned */
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /*---------- Initialize Write Data ----------*/
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        g_src[i] = (uint8_t)i;   /* cast to uint8_t */
    }

    /*---------- Write Data via write API ----------*/
    uint8_t * dest = (uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_ADDRESS);  /* xSPI1_CS0 memory, non-cache area use. */
    err = R_XSPI_QSPI_Write(&g_qspi0_ctrl, g_src, dest, DATA_SIZE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE] OK\r\n");
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write2;
    do
    {
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MICROSECONDS);
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write2);
    } while (true == status_write2.write_in_progress);

    /*---------- Enter Quad mode ----------*/
    qspi_set_Quad_Mode_enable();

    /*---------- Direct transfer (READ) ----------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_read =
    {
        .command        = 0xEBU,  /* Quad I/O Fast Read instruction */
        .address        = 0x000234U,
        .data           = 0U,
        .command_length = 1U,
        .address_length = 3U,
        .data_length    = 1U,

         /* 4READ instruction needs (2+4) dummy cycles */
        .dummy_cycles   = 6U
    };
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_read, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[DIRECT TRANSFER READ] failed: %d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[DIRECT TRANSFER READ] CMD=0x%02X addr=0x%08X dummy=%u LEN=%u -> 0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_read.command,
                    (unsigned) qspi_test_direct_transfer_read.address,
                    (unsigned) qspi_test_direct_transfer_read.dummy_cycles,
                    (unsigned) qspi_test_direct_transfer_read.data_length,
                    (unsigned) qspi_test_direct_transfer_read.data);
    }

    /*---------- Verify Write data = Read data? ----------*/
    if (qspi_test_direct_transfer_read.data != qspi_test_direct_transfer_write.data)
    {
        /* Exit Quad mode */
        APP_ERR_PRINT("[VERIFY] mismatch: wrote=0x%02X read=0x%02X\r\n",
                        qspi_test_direct_transfer_write.data, qspi_test_direct_transfer_read.data);
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    else
    {
        APP_PRINT("[VERIFY] direct transfer OK\r\n");
    }

    /*---------- Read data using memory-mapping mode ----------*/
    uint32_t read_buffer = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 +  qspi_test_direct_transfer_write.address); /* xSPI0_CS0 memory (Mirror area) */

    /*---------- Verify Write data = Read data? ----------*/
    if (read_buffer != qspi_test_direct_transfer_write.data)
    {
        /* Exit Quad mode */
        APP_ERR_PRINT("[VERIFY] mismatch: wrote=0x%02X read=0x%02X\r\n",
                        qspi_test_direct_transfer_write.data, qspi_test_direct_transfer_read.data);
        qspi_set_Quad_Mode_disable();
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    else
    {
        APP_PRINT("[VERIFY] mapped read OK\r\n");
    }

    /*---------- Verify data written via write API ----------*/
    volatile uint8_t dummy_read;
    FSP_PARAMETER_NOT_USED(dummy_read);
    for (uint32_t i = 0; i < DATA_SIZE; i++)
    {
        uint8_t src_data = g_src[i];
        uint8_t dest_data = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_ADDRESS + i);   /* cast to uint8_t */
        if (src_data != dest_data)
        {
            /* Exit Quad mode */
            APP_ERR_PRINT("[VERIFY] mismatch @+%u: w=0x%02X r=0x%02X\r\n",
                            (unsigned)i, (unsigned)src_data, (unsigned)dest_data);
            qspi_set_Quad_Mode_disable();
            APP_ERR_TRAP(FSP_ERR_ASSERTION);
        }

        /* If least significant 2 bits of dest_Data address are 0x02, put dummy read sequence to deactivate unintentional Continuous Read Mode */
        if ((i & 0x03) == 0x02)
        {
            dummy_read = *(uint8_t *)(QSPI_DEVICE_START_ADDRESS - 0x20000000 + WRITE_ADDRESS);   /* cast to uint8_t */
        }
    }

    APP_PRINT("[VERIFY] write API OK\r\n");

    /* Exit Quad mode */
    qspi_set_Quad_Mode_disable();
    APP_PRINT("[EXIT] Quad mode disabled\r\n");

    /* Close the application */
    APP_PRINT("[DONE]\r\n");
    while (1)
    {
        ; /* Do nothing */
    }
}

void qspi_set_Quad_Mode_enable(void)
{
    /* For following settings, temporary set protocol 1S-1S-1S */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*---------------- Read status register2(RDSR2) (35h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;

    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR2.command,
                    (unsigned) direct_command_RDSR2.data_length,
                    (unsigned) (direct_command_RDSR2.data & 0xFFU));
    }
    uint32_t read_status2 = direct_command_RDSR2.data;

    /*---------------- Write enable (06h)----------------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06;
    qspi_test_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE ENABLE] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE ENABLE] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_write_enable.command,
                    (unsigned) qspi_test_direct_transfer_write_enable.data_length,
                    (unsigned) (qspi_test_direct_transfer_write_enable.data & 0xFFU));
    }

    /*---------------- Write Status Register-2 (31h) (set QE bit 1) ----------------*/
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = 0x02 | read_status2;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;

    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_transfer_register_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_transfer_register_write.command,
                    (unsigned) direct_transfer_register_write.data_length,
                    (unsigned) (direct_transfer_register_write.data & 0xFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);

    /* 1S-4S-4S protocol settings. */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_4S_4S);
}

void qspi_set_Quad_Mode_disable(void)
{
    /* 1S-1S-1S protocol settings. */
    R_XSPI_QSPI_SpiProtocolSet(&g_qspi0_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);

    /*---------------- Read status register2(RDSR2) (35h) ---------------*/
    spi_flash_direct_transfer_t direct_command_RDSR2 = {0};
    direct_command_RDSR2.command        = 0x35U;
    direct_command_RDSR2.command_length = 1U;
    direct_command_RDSR2.data_length    = 1U;
    fsp_err_t err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_command_RDSR2, SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
    
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[READ STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[READ STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_command_RDSR2.command,
                    (unsigned) direct_command_RDSR2.data_length,
                    (unsigned) (direct_command_RDSR2.data & 0xFFU));
    }
    uint32_t read_status = direct_command_RDSR2.data;

    /*---------------- Write enable (06h) ----------------*/
    spi_flash_direct_transfer_t qspi_test_direct_transfer_write_enable = {0};
    qspi_test_direct_transfer_write_enable.command        = 0x06;
    qspi_test_direct_transfer_write_enable.command_length = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &qspi_test_direct_transfer_write_enable, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE ENABLE] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE ENABLE] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) qspi_test_direct_transfer_write_enable.command,
                    (unsigned) qspi_test_direct_transfer_write_enable.data_length,
                    (unsigned) (qspi_test_direct_transfer_write_enable.data & 0xFFU));
    }

    /*---------------- Write Status Register-2 (31h) (set QE bit 0) ----------------*/
    spi_flash_direct_transfer_t direct_transfer_register_write = {0};
    direct_transfer_register_write.command              = 0x31;
    direct_transfer_register_write.data                 = read_status & 0xfd;
    direct_transfer_register_write.command_length       = 1U;
    direct_transfer_register_write.data_length          = 1U;
    err = R_XSPI_QSPI_DirectTransfer(&g_qspi0_ctrl, &direct_transfer_register_write, SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("[WRITE STATUS REGISTER] DirectTransfer failed: err=%d\r\n", err);
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("[WRITE STATUS REGISTER] info: CMD=0x%02X, LEN=%u -> 0x%02X\r\n",
                    (unsigned) direct_transfer_register_write.command,
                    (unsigned) direct_transfer_register_write.data_length,
                    (unsigned) (direct_transfer_register_write.data & 0xFFU));
    }

    /* Wait for status register to update. */
    spi_flash_status_t status_write;
    do
    {
        (void)R_XSPI_QSPI_StatusGet(&g_qspi0_ctrl, &status_write);
    } while (true == status_write.write_in_progress);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_xspi_qspi_ep)
 **********************************************************************************************************************/
