/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "usb_hhid_ep.h"

/***********************************************************************************************************************
 * @addtogroup usb_hhid_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

static uint8_t  s_hid_type;
static uint16_t s_mxps;
static uint8_t  s_store_buf[BUFSIZE];

extern uint8_t g_buf[USB_RCV_BUF_SIZE];              /* USB Receive data */

static void deinit_usb (void);

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    fsp_pack_version_t  version               =  {RESET_VALUE};

    usb_status_t     event;

    usb_event_info_t event_info;

    uint16_t         offset = 0;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    
    /* Print the EP information on the RTT viewer */
    APP_PRINT (EP_INFO);

    err = R_USB_Open(&g_basic0_ctrl, &g_basic0_cfg);

    /* Error Handle */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nError in initializing USB Host CDC\r\n");
        APP_ERR_TRAP (err);
    }

    while (1)
    {
#if (BSP_CFG_RTOS == 2)
        USB_APL_RCV_MSG(USB_APL_MBX, (usb_msg_t **) &p_mess);
        event_info = *p_mess;
        event      = event_info.event;
#else
        /* Get event code */
        err = R_USB_EventGet(&event_info, &event);

        /* Error Handle */
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT ("\r\nError in get events USB Host CDC\r\n");
            APP_ERR_TRAP (err);
        }
#endif

        switch (event)
        {
            case USB_STATUS_CONFIGURED:
            {
                err = R_USB_HHID_TypeGet(&g_basic0_ctrl, &s_hid_type, USB_FS_DEVICE_ADDRESS_1);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT ("** R_USB_HHID_TypeGet API FAILED **\r\n");

                    /* Close the opened USB driver and trap error.*/
                    deinit_usb();
                    APP_ERR_TRAP(err);
                }

                err = R_USB_HHID_MaxPacketSizeGet(&g_basic0_ctrl, &s_mxps, USB_HID_IN, USB_FS_DEVICE_ADDRESS_1);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT ("** R_USB_HHID_MaxPacketSizeGet API FAILED **\r\n");

                    /* Close the opened USB driver and trap error.*/
                    deinit_usb();
                    APP_ERR_TRAP(err);
                }

                /* Send the HID request (SetProtocol) to HID device */
                err = set_protocol(&g_basic0_ctrl, BOOT_PROTOCOL, USB_FS_DEVICE_ADDRESS_1);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT ("** Send the HID request(SetProtocol) to HID device FAILED **\r\n");

                    /* Close the opened USB driver and trap error.*/
                    deinit_usb();
                    APP_ERR_TRAP(err);
                }
                break;
            }

            case USB_STATUS_READ_COMPLETE:
            {
                offset = hid_memcpy(s_store_buf, g_buf, offset, s_mxps);

                /* cast to uint32_t */
                err = R_USB_Read(&g_basic0_ctrl, g_buf, (uint32_t)s_mxps, USB_FS_DEVICE_ADDRESS_1);

                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    APP_ERR_PRINT ("** R_USB_Read API FAILED **\r\n");

                    /* Close the opened USB driver and trap error.*/
                    deinit_usb();
                    APP_ERR_TRAP(err);
                }
                output_log();
                break;
            }

            case USB_STATUS_REQUEST_COMPLETE:
            {
                APP_PRINT("USB Status Request Completed Successfully\r\n");

                if (USB_HID_SET_PROTOCOL == (event_info.setup.request_type & USB_BREQUEST))
                {
                    /* cast to uint32_t */
                    err = R_USB_Read(&g_basic0_ctrl, g_buf, (uint32_t)s_mxps, USB_FS_DEVICE_ADDRESS_1);

                    /* Handle error */
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT ("** R_USB_Read API FAILED **\r\n");

                        /* Close the opened USB driver and trap error.*/
                        deinit_usb();
                        APP_ERR_TRAP(err);
                    }
                    output_log();
                }

                APP_PRINT("\r\nEnter any key as specified from a to z, A to Z, 0 to 9 "
                        "and any special character on keyboard\r\n\n");
                break;
            }

            default:
            {
                break;
            }
        }
    }
}

/***********************************************************************************************************************
 * @fn        deinit_usb
 * @brief     This function is called to do closing of usb module using its HAL level API.
 *            Close the usb module. Handle the Error internally with Proper Message.
 *            Application handles the rest.
 * @param[IN] None
 * @retval    None
 **********************************************************************************************************************/
static void deinit_usb(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* close opened USB module */
    err = R_USB_Close(&g_basic0_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("** R_USB_Close API FAILED **\r\n");
    }
}
/***********************************************************************************************************************
 * End of function: deinit_usb
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup usb_pcdc_ep)
 **********************************************************************************************************************/

