/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "mtu3_poe3_ep.h"
 
/***********************************************************************************************************************
 * @addtogroup r_mtu3_ep
 * @{
 **********************************************************************************************************************/

/* the previous status of the SW2 button */
uint8_t g_u8_sw2_old = MAIN_SW_STATUS_OFF; 

/* Define the units to be used with the software delay function */
const bsp_delay_units_t g_bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;

/* Set the blink frequency (must be <= g_bsp_delay_units */
const uint32_t g_freq_in_hz = 5;

/* Calculate the delay in terms of g_bsp_delay_units */
const uint32_t g_delay = g_bsp_delay_units / g_freq_in_hz;

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err =  FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* MTU3_THREE_PHASE driver and POE3 driver initialization*/
    err = init_mtu3_three_phase_and_poe3();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** MTU3_THREE_PHASE driver and POE3 driver initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* MTU3_THREE_PHASE start */
    err = R_MTU3_THREE_PHASE_Start(&g_three_phase_ctrl);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("R_MTU3_THREE_PHASE_Start API failed \r\n");
        APP_ERR_TRAP(err);
    }

    /* LED OFF */
    clear_led();

    /* LED0 ON */
    set_led(LED_0);

    while (1)
    {
        /* Handle SW2 */
        if ((MAIN_SW_STATUS_OFF == g_u8_sw2_old) && (MAIN_SW_STATUS_ON == MAIN_SW2_NB)) /* SW2 pressed */
        {
            g_u8_sw2_old = MAIN_SW_STATUS_ON;
            r_main_mtu_chng_duty();
            
            /* Delay */
            R_BSP_SoftwareDelay(g_delay, g_bsp_delay_units);
        }
        else 
        {
            if (MAIN_SW_STATUS_ON != MAIN_SW2_NB) /* SW2 released */
            {
                g_u8_sw2_old = MAIN_SW_STATUS_OFF;
            }
        }

        /* Handle SW1 */
        if (MAIN_SW_STATUS_ON == MAIN_SW1_NB)
        {
            err = R_POE3_OutputDisable(&g_poe3_ctrl);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n ** R_POE3_OutputDisable API failed ** \r\n");
                APP_ERR_TRAP(err);
            }
            
            /* break */
            break;
        }
    }

    /* LED OFF */
    clear_led();

    /* LED1 ON */
    set_led(LED_1);

    /* Deinitialize MTU3 three phase driver and POE3 driver*/
    err = deinit_mtu3_three_phase_and_poe3();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** MTU3_THREE_PHASE driver and POE3 driver Deinitialize FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    while (1)
    {
        ; /* Do nothing */
    }

}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup r_mtu3_ep)
 **********************************************************************************************************************/
