/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "bsc_sdram_ep.h"

static uint16_t s_p_src[DATA_NUM];
static uint16_t s_p_dest[DATA_NUM];

/***********************************************************************************************************************
 * @addtogroup bsc_sdram_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart (bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version =   { RESET_VALUE };

    /* Get the FSP version */
    R_FSP_VersionGet (&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);

    /* Print the EP information on the RTT viewer */
    APP_PRINT(EP_INFO);

    /* Initialize BSC_SDRAM driver */
    err = R_BSC_SDRAM_Open (&g_sdram_ctrl, &g_sdram_cfg);

    if (FSP_SUCCESS != err)
    {   /* BSC_SDRAM module init failed */
        APP_PRINT("\r\n ** BSC_SDRAM INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Prepare write data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        s_p_src[i] = i;
    }

    APP_PRINT("\r\nBSC_SDRAM writes data from 0 to 512 to the CS3 mirror area connected to SDRAM.\r\n");

    /* Write data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        *((uint16_t *) BSC_SDRAM_CS3_MIRROR_SPACE + i) = s_p_src[i];
    }

    APP_PRINT("\r\nBSC_SDRAM reads back the previously written area.\r\n");

    /* Read data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        s_p_dest[i] = *((uint16_t *) BSC_SDRAM_CS3_MIRROR_SPACE + i);
    }

    /* Verify data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        if (s_p_src[i] != s_p_dest[i])
        {
            /* Verify data after writing failure message */
            APP_ERR_PRINT ("\r\n** BSC_SDRAM VERIFY DATA FAILED**\r\n");
            APP_ERR_TRAP(err);
        }
    }

    __asm volatile("nop"); /* This nop is for debug. No need for SDRAM operation. */

    APP_PRINT("\r\nBSC_SDRAM writes data 0xFFFF to the CS3 mirror area connected to SDRAM.\r\n");

    /* Write data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        *((uint16_t *) BSC_SDRAM_CS3_MIRROR_SPACE + i) = 0xFFFF;
    }

    /* Read data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        s_p_dest[i] = *((uint16_t *) BSC_SDRAM_CS3_MIRROR_SPACE + i);
    }

    APP_PRINT("\r\nBSC_SDRAM reads back the previously written area.\r\n");

    /* Verify data. */
    for (uint16_t i = 0; i < DATA_NUM; i++)
    {
        if (0xFFFF != s_p_dest[i])
        {
            /* Verify data after writing failure message */
            APP_ERR_PRINT("\r\n** BSC_SDRAM VERIFY DATA FAILED**\r\n");
            APP_ERR_TRAP(err);
        }
    }

        APP_PRINT("\r\nBSC_SDRAM Demo Completion.\r\n");

    while (true)
    {
        ;
    }
}

/***********************************************************************************************************************
 * @brief     User defined BSC_SDRAM callback function.
 * @param[IN] p_args  Callback arguments from the BSC_SDRAM driver.
 * @retval    None
 **********************************************************************************************************************/
void user_bsc_sdram_callback (bsc_sdram_callback_args_t * p_args)
{
    /* The callback function is called each time the BSC issues a REF. */
    FSP_PARAMETER_NOT_USED(p_args);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
    #if (1 == BSP_CFG_DDR_INIT_ENABLE)

        /* Initialize the DDR settings. */
        bsp_ddr_init();
    #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup bsc_sdram_ep)
 **********************************************************************************************************************/
