/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "spi_ep.h"
#include "stdbool.h"

/***********************************************************************************************************************
 * @addtogroup spi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    uint8_t converted_rtt_input = RESET_VALUE;

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize SPI driver */
    err = spi_init();

    if (FSP_SUCCESS != err)
    {   /* SPI module init failed */
        APP_PRINT("\r\n ** SPI INIT FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** SPI INIT SUCCESSFUL ** \r\n");
    }

    /* Menu for User Selection */
    APP_PRINT("\r\nSelect from the below Menu options\r\n");
    APP_PRINT("\r\nPress 1 for Write() and Read()");
    APP_PRINT("\r\nPress 2 for WriteRead()");
    APP_PRINT("\r\nPress 3 to Exit\r\n");

    while (EXIT != converted_rtt_input)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            converted_rtt_input = (uint8_t)atoi((char *)rByte);

            switch (converted_rtt_input)
            {
                case WRITE_AND_READ:
                    err = spi_write_and_read ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo failed **  \r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** SPI WRITE AND READ Demo Successful**  \r\n");
                    }
                    break;
                case WRITE_READ:
                    err = spi_write_read ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("\r\n** SPI WRITE_READ Demo failed **  \r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE_READ Demo Successful**  \r\n");
                    }
                    break;
                case EXIT:
                    err = spi_exit_demo();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI EXIT Demo failed ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI EXIT Demo Successful ** \r\n");
                    }
                    break;
                default:

                    /* Menu for User Selection */
                    APP_PRINT("\r\nSelect from the below Menu options\r\n");
                    APP_PRINT("\r\nPress 1 for Write() and Read()");
                    APP_PRINT("\r\nPress 2 for WriteRead()");
                    APP_PRINT("\r\nPress 3 to Exit\r\n");
                    break;
            }
            if ((WRITE_AND_READ <= converted_rtt_input) && (EXIT > converted_rtt_input))
            {
                APP_PRINT ("\r\nEnter any other key to go back to the main menu\r\n");
            }
        }
    }

    APP_PRINT(RTT_CTRL_TEXT_BRIGHT_CYAN "\r\nExiting SPI demo....\r\n" RTT_CTRL_RESET);
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}

/***********************************************************************************************************************
 * @} (end addtogroup spi_ep)
 **********************************************************************************************************************/
