/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "r_rtc.h"
#include "rtc_ep.h"
#include "common_utils.h"

/***********************************************************************************************************************
 * @addtogroup r_rtc_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/* rtc_time_t is an alias for the C Standard time.h struct 'tm' */
rtc_time_t set_time =
{
    .tm_sec  = 50,
    .tm_min  = 0,
    .tm_hour = 11,
    .tm_mday = 23,
    .tm_wday = 4,
    .tm_mon  = 3,
    .tm_year = YEARS_SINCE_1900,
};

/* Hardware alarm test:
 * Start time : 23/04/2026 11:00:50 (RTC weekday = Thursday)
 * Alarm triggers at 11:01 when hour + minute match and the current weekday (Thursday) is enabled
 */

static const rtc_alarm_time_t g_alarm_time =
{
    .time =
    {
        .tm_hour = 11,
        .tm_min  = 1,
    },
    .hour_match      = true,
    .min_match       = true,
    .thursday_match  = true,
    .channel         = RTC_ALARM_CHANNEL_0,
};

static rtc_time_t get_time;
volatile uint32_t g_rtc_get_flg = 0;
volatile uint32_t g_rtc_alarm_flg = 0;

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err =  FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
            version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize the RTC module */
    err = R_RTC_Open(&g_rtc0_ctrl, &g_rtc0_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_RTC_Open API failed\r\n");
        APP_ERR_TRAP(err);
    }

    /* R_RTC_CalendarTimeSet must be called at least once to start the RTC */
    R_RTC_CalendarTimeSet(&g_rtc0_ctrl, &set_time);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_RTC_CalendarTimeSet API failed\r\n");
        APP_ERR_TRAP(err);
    }

    /* Set hardware alarm */
    err = R_RTC_CalendarAlarmSet(&g_rtc0_ctrl, (rtc_alarm_time_t *) &g_alarm_time);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_RTC_CalendarAlarmSet API failed\r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\r\n[RTC] Hardware alarm is set at %02d:%02d\r\n", g_alarm_time.time.tm_hour, g_alarm_time.time.tm_min);

    /* Set the periodic interrupt rate to 1 second */
    R_RTC_PeriodicIrqRateSet(&g_rtc0_ctrl, RTC_PERIODIC_IRQ_SELECT_1_SECOND);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("R_RTC_PeriodicIrqRateSet API failed\r\n");
        APP_ERR_TRAP(err);
    }
    APP_PRINT("\r\n\r\n");

    /* Wait for the periodic interrupt */
    while (1)
    {

        if (1 == g_rtc_get_flg)
        {
            g_rtc_get_flg = 0;
            APP_PRINT("\r%02d/%02d/%04d %02d:%02d:%02d", get_time.tm_mon + 1, get_time.tm_mday, get_time.tm_year + 1900,
                    get_time.tm_hour, get_time.tm_min, get_time.tm_sec);
            fflush(stdout);
        }
        if (1 == g_rtc_alarm_flg)
        {
            g_rtc_alarm_flg = 0;
            APP_PRINT("\r\n[RTC] SOFTWARE ALARM TRIGGERED\r\n");
        }
    }
}

/***********************************************************************************************************************
 * @brief      This is RTC callback ISR for periodic time updates and hardware alarm events.
 *             The alarm interrupt is triggered only when hour, minute, and the enabled
 *             day-of-week match the current RTC calendar time.
 * @param[IN]  p_args  Pointer to the RTC callback arguments structure.
 * @retval     None.
 **********************************************************************************************************************/
void rtc_ep_callback (rtc_callback_args_t * p_args)
{
    switch (p_args->event)
    {
        case RTC_EVENT_ALARM_IRQ:
        {
            g_rtc_alarm_flg = 1;
            break;
        }
        case RTC_EVENT_PERIODIC_IRQ:
        {
            /* Get the calendar time */
            R_RTC_CalendarTimeGet(&g_rtc0_ctrl, &get_time);
            g_rtc_get_flg = 1;
            break;
        }
        default:
        {
            break;
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void)
{
    /* The very beginning of the startup process. */

    /* Do not delete. Required to return to system_init. */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_rtc_ep)
 **********************************************************************************************************************/

