/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "mtu3_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_mtu3_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @fn         hal_entry
 * @brief      hal_entry function.
 * @retval     None
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err =  FSP_SUCCESS;

    fsp_pack_version_t version = {RESET_VALUE};

    /* Get the FSP version */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
        version.version_id_b.patch);

    APP_PRINT(EP_INFO);

    err = init_mtu3();

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n ** MTU3 driver initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }

    /* Start the timer. */
    err = R_MTU3_Start(&g_timer0_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("R_MTU3_Start API failed \r\n");
        APP_ERR_TRAP(err);
    }

    while (1)
    {
        /* Delay */
        R_BSP_SoftwareDelay(2U, BSP_DELAY_UNITS_SECONDS);

        /* Change Timer */
        r_main_mtu_change_timer();
    }
}
/***********************************************************************************************************************
 * End of function: hal_entry
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
/***********************************************************************************************************************
 * End of function: R_BSP_WarmStart
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * @} (end addtogroup r_mtu3_ep)
 **********************************************************************************************************************/
