/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2024 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "bsp_multi_ep.h"

/***********************************************************************************************************************
 * @addtogroup r_bsp_multi_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void                         R_BSP_WarmStart(bsp_warm_start_event_t event) BSP_PLACE_IN_SECTION(".warm_start");
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess(void) BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

volatile uint32_t g_timer_count = 0; /* 1 count = 50[ms] */
/***********************************************************************************************************************
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Initialize the CMT module */
    err = R_CMT_Open(&g_timer_ctrl, &g_timer_cfg);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* CMT module initialization failed */
        APP_ERR_TRAP(err);
    }

    /* Start CMT timer */
    err = R_CMT_Start(&g_timer_ctrl);

    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* Close CMT timer */
        if ((R_CMT_Close(&g_timer_ctrl) != FSP_SUCCESS))
        {
            APP_ERR_TRAP(err);
        }
        APP_ERR_TRAP(err);
    }

    /* Turn off LED */
    R_BSP_PinClear((bsp_io_region_t)REGION, (bsp_io_port_pin_t)LED2);

    /* Infinite loop */
    while (1)
    {
        /* Toggle LED */
        R_BSP_PinToggle((bsp_io_region_t)REGION, (bsp_io_port_pin_t)LED2);

        /* Delay 500ms */
        g_timer_count = 0;
        while (10 > g_timer_count)
        {
            ; /* Do nothing */
        }
    }
}

/***********************************************************************************************************************
 * @brief     This is user timer callback.
 * @param[in] p_args  Pointer to timer_callback_args_t from the timer driver.
 * @return    None.
 **********************************************************************************************************************/
void user_timer_callback (timer_callback_args_t * p_args)
{
    if (TIMER_EVENT_CYCLE_END == p_args->event)
    {
        g_timer_count++;
    }
}

/***********************************************************************************************************************
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        }
    }
}

/***********************************************************************************************************************
 * This function is called without a stack at the very beginning of the startup process.
 * All instructions must be written in inline assembly.
 **********************************************************************************************************************/
BSP_ATTRIBUTE_STACKLESS void R_BSP_WarmStart_StackLess (void)
{
    /* The very beginning of the startup process */

    /* Do not delete. Required to return to system_init */
#if (0 == BSP_LP64_SUPPORT)
    __asm volatile ("BX lr");
#else
    __asm volatile ("BR lr");
#endif
}

/***********************************************************************************************************************
 * @} (end addtogroup r_bsp_multi_ep)
 **********************************************************************************************************************/
